export const DEFAULT_CONCERT_LINK = "https://www.mphil.de/konzerte-und-karten/kalender-2024-2025#j44933";

const concerts = [
  {
    date: "2025-06-06 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "H4",
    programm: "Atmosph\u00e8res; Sinfonie Nr.2; Konzert f\u00fcr Violine und Orchester D-Dur",
    title: null,
    composers: "Ligeti; Brahms; Strawinsky",
    composerGivenNames: "Gy\u00f6rgy; Johannes; Igor",
    titles: null,
    duration: "01:12:00",
    soloistsLastNames: "Kavakos",
    soloistsGivenNames: "Leonidas",
    instruments: "Violine",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-06 00:00:00",
    start: "21:00:00",
    type: "MPhil Late",
    venue: "Halle E",
    city: "M\u00fcnchen",
    series: null,
    programm: null,
    title: null,
    composers: null,
    composerGivenNames: null,
    titles: null,
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 0,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-07 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "Atmosph\u00e8res; Sinfonie Nr.2; Konzert f\u00fcr Violine und Orchester D-Dur",
    title: null,
    composers: "Ligeti; Brahms; Strawinsky",
    composerGivenNames: "Gy\u00f6rgy; Johannes; Igor",
    titles: null,
    duration: "01:12:00",
    soloistsLastNames: "Kavakos",
    soloistsGivenNames: "Leonidas",
    instruments: "Violine",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-13 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "Pr\u00e9lude \u00e0 l'apr\u00e8s-midi d'un faune; Wesendonck Lieder (5 Titel); Symphonie Fantastique",
    title: null,
    composers: "Debussy; Wagner; Berlioz",
    composerGivenNames: "Claude; Richard; Hector",
    titles: null,
    duration: "01:25:00",
    soloistsLastNames: "Willis-S\u00f8rensen",
    soloistsGivenNames: "Rachel",
    instruments: "Solistin Stimmlage Sopran\"   \"",
    conductorLastName: "Nelsons",
    conductorGivenNames: "Andris",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-14 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "F; I",
    programm: "Wesendonck Lieder (5 Titel); Symphonie Fantastique; Pr\u00e9lude \u00e0 l'apr\u00e8s-midi d'un faune",
    title: null,
    composers: "Wagner; Berlioz; Debussy",
    composerGivenNames: "Richard; Hector; Claude",
    titles: null,
    duration: "02:50:00",
    soloistsLastNames: "Willis-S\u00f8rensen",
    soloistsGivenNames: "Rachel",
    instruments: "Solistin Stimmlage Sopran\"   \"",
    conductorLastName: "Nelsons",
    conductorGivenNames: "Andris",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-22 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Streichtrio; Streichquartett F-Dur op. 35; Streichquartett g-Moll, op. 10",
    title: "Dreimalig einmalig \u2013 8. Kammerkonzert",
    composers: "Francaix; Ravel; Debussy",
    composerGivenNames: "Jean; Maurice; Claude",
    titles: "Dreimalig einmalig \u2013 8. Kammerkonzert",
    duration: "04:28:00",
    soloistsLastNames: "Stark; Risbet; Mijnders; Vaud\u00e9",
    soloistsGivenNames: "Asami; Julie Amandine Laure; Floris; C\u00e9line Marie",
    instruments: "2. Violine; Bratsche; Violoncello; 1. Violine",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-24 00:00:00",
    start: "19:30:00",
    type: "Sonderkammerkonzert",
    venue: "Rathaussaal",
    city: "M\u00fcnchen",
    series: null,
    programm: "Ouvert\u00fcre zu The Boatswain's Mate\"   \"; Suite aus Les Bor\u00e9ades\"  \"; Voodoo Dolls; Improvisation \u00fcber Tonmaterial aus explosante fixe von Pierre Boulez; Sinfonia in F-Dur; Strum; Streichquintett Es-Dur; Ouverture zu C\u00e9phale et Procris\"   \"; Sinfonie Nr. 3 g-moll op. 36; Leyendas: An Andean Walkabout; Intermezzo fun\u00e8bre",
    title: "Regenbogen-Konzert",
    composers: "Smyth; Rameau; Montgomery; Strauch; Ahlefeldt; Farrenc; Jaquet de La Guerre; Frank",
    composerGivenNames: "Dame Ethel Mary; Jean-Philippe; Jessie; Alexander; Maria Theresia von; Louise; \u00c9lisabeth-Claude; Gabriela Lena",
    titles: "Regenbogen-Konzert",
    duration: "06:45:00",
    soloistsLastNames: "Weiskopf; Tolpygo; Zaunschirm; Rieke; Arnholdt",
    soloistsGivenNames: "Alexander Franz; Vladimir; Johanna; Jannis Michael; Friederike Luise",
    instruments: "Kontraba\u00df; 1. Violine; 2. Violine; Bratsche; Violoncello",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 0,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-26 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "The planets; Klavierkonzert Nr. 3",
    title: "Rachmaninow / Holst",
    composers: "Holst; Rachmaninoff",
    composerGivenNames: "Gustav; Sergei",
    titles: "Rachmaninow / Holst",
    duration: "01:32:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Sorita",
    soloistsGivenNames: "Kyohei",
    instruments: "Chor; Solopianist/ in",
    conductorLastName: "Gimeno",
    conductorGivenNames: "Gustavo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-27 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "Jugendkonzert",
    programm: "The planets; Klavierkonzert Nr. 3",
    title: "Uni-Konzert & U30 \u2013 Rachmaninow/Holst",
    composers: "Holst; Rachmaninoff",
    composerGivenNames: "Gustav; Sergei",
    titles: "Uni-Konzert & U30 \u2013 Rachmaninow/Holst",
    duration: "01:32:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Sorita",
    soloistsGivenNames: "Kyohei",
    instruments: "Chor; Solopianist/ in",
    conductorLastName: "Gimeno",
    conductorGivenNames: "Gustavo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-06-29 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "The planets; Klavierkonzert Nr. 3",
    title: "Rachmaninow / Holst",
    composers: "Holst; Rachmaninoff",
    composerGivenNames: "Gustav; Sergei",
    titles: "Rachmaninow / Holst",
    duration: "01:32:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Sorita",
    soloistsGivenNames: "Kyohei",
    instruments: "Chor; Solopianist/ in",
    conductorLastName: "Gimeno",
    conductorGivenNames: "Gustavo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-07-02 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "Violinkonzert; Sinfonie Nr.9 (Aus der Neuen Welt\")  \"",
    title: "Brahms / Dvo\u0159\u00e1k",
    composers: "Brahms; Dvorak",
    composerGivenNames: "Johannes; Antonin",
    titles: "Brahms / Dvo\u0159\u00e1k",
    duration: "01:16:00",
    soloistsLastNames: "Hahn",
    soloistsGivenNames: "Hilary",
    instruments: "Violine",
    conductorLastName: "Orozco-Estrada",
    conductorGivenNames: "Andr\u00e9s",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-07-03 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "F; G4",
    programm: "Violinkonzert; Sinfonie Nr.9 (Aus der Neuen Welt\")  \"",
    title: "Brahms / Dvo\u0159\u00e1k",
    composers: "Brahms; Dvorak",
    composerGivenNames: "Johannes; Antonin",
    titles: "Brahms / Dvo\u0159\u00e1k",
    duration: "02:32:00",
    soloistsLastNames: "Hahn",
    soloistsGivenNames: "Hilary",
    instruments: "Violine",
    conductorLastName: "Orozco-Estrada",
    conductorGivenNames: "Andr\u00e9s",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-07-13 00:00:00",
    start: "20:00:00",
    type: "Konzert Open Air",
    venue: "Odeonsplatz, Feldherrnhalle",
    city: "M\u00fcnchen",
    series: null,
    programm: "Violinkonzert D-Dur; Sinfonische T\u00e4nze",
    title: "Klassik am Odeonsplatz",
    composers: "Beethoven; Rachmaninoff",
    composerGivenNames: "Ludwig van; Sergei",
    titles: "Klassik am Odeonsplatz",
    duration: "01:19:00",
    soloistsLastNames: "Batiashvili",
    soloistsGivenNames: "Elisabeth",
    instruments: "Solist /-in Violine\"   \"",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 0,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-07-16 00:00:00",
    start: "10:00:00",
    type: "Kinderkonzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: null,
    programm: "Konferenz der Tiere; Kammersinfonie f\u00fcr Streichorchester; Suite Mignonne; Valse Triste; Arlequin",
    title: "Die Konferenz der Tiere \u2013 Kinderkonzert",
    composers: "diverse Komponisten; Schostakowitsch; Sibelius; Hoffmann",
    composerGivenNames: "Dmitrij; Jean; E.T.A.",
    titles: "Die Konferenz der Tiere \u2013 Kinderkonzert",
    duration: "01:58:52",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: "Yoon",
    conductorGivenNames: "Hankyeol",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-09-09 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "E4",
    programm: "Sinfonie Nr.8 (Unvollendete\")  \"; Konzert f\u00fcr Violoncello; Tristan: Vorspiel und Isoldes Liebestod",
    title: "Elger Schubert Wagner",
    composers: "Schubert; Elgar; Wagner",
    composerGivenNames: "Franz; Edward; Richard",
    titles: "Elger Schubert Wagner",
    duration: "01:10:00",
    soloistsLastNames: "Gabetta",
    soloistsGivenNames: "Sol",
    instruments: "Violoncello",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-09-10 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "Konzert f\u00fcr Violoncello; Tristan: Vorspiel und Isoldes Liebestod; Sinfonie Nr.8 (Unvollendete\")  \"",
    title: "Elger Schubert Wagner",
    composers: "Elgar; Wagner; Schubert",
    composerGivenNames: "Edward; Richard; Franz",
    titles: "Elger Schubert Wagner",
    duration: "01:10:00",
    soloistsLastNames: "Gabetta",
    soloistsGivenNames: "Sol",
    instruments: "Violoncello",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-09-27 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "F; I",
    programm: "Sinfonie Nr.8; Klavierkonzert Nr. 3; Peer Gynt-Suite Nr.1",
    title: "Grieg Prokofjew Dvorak",
    composers: "Dvorak; Prokofieff; Grieg",
    composerGivenNames: "Antonin; Sergej; Edvard",
    titles: "Grieg Prokofjew Dvorak",
    duration: "02:36:00",
    soloistsLastNames: "Montero",
    soloistsGivenNames: "Gabriela",
    instruments: "Solopianist/ in",
    conductorLastName: "Stasevska",
    conductorGivenNames: "Dalia",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-09-28 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "Sinfonie Nr.8; Klavierkonzert Nr. 3; Peer Gynt-Suite Nr.1",
    title: "Grieg Prokofjew Dvorak",
    composers: "Dvorak; Prokofieff; Grieg",
    composerGivenNames: "Antonin; Sergej; Edvard",
    titles: "Grieg Prokofjew Dvorak",
    duration: "01:18:00",
    soloistsLastNames: "Montero",
    soloistsGivenNames: "Gabriela",
    instruments: "Solopianist/ in",
    conductorLastName: "Stasevska",
    conductorGivenNames: "Dalia",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-08 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "Le Corsaire; Les nuits d'\u00e9t\u00e9 - Sommern\u00e4chte; La mer; Ca\u00edda libre",
    title: "Brunea-Boulmier Berlioz Debussy",
    composers: "Berlioz; Debussy; Bruneau-Boulmier",
    composerGivenNames: "Hector; Claude; Rodolphe",
    titles: "Brunea-Boulmier Berlioz Debussy",
    duration: "01:12:00",
    soloistsLastNames: "Crebassa",
    soloistsGivenNames: "Marianne",
    instruments: "Solistin Stimmlage Mezzosopran\"  \"",
    conductorLastName: "Nagano",
    conductorGivenNames: "Kent",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-09 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "Le Corsaire; Les nuits d'\u00e9t\u00e9 - Sommern\u00e4chte; La mer; Ca\u00edda libre",
    title: "Brunea-Boulmier Berlioz Debussy",
    composers: "Berlioz; Debussy; Bruneau-Boulmier",
    composerGivenNames: "Hector; Claude; Rodolphe",
    titles: "Brunea-Boulmier Berlioz Debussy",
    duration: "01:12:00",
    soloistsLastNames: "Crebassa",
    soloistsGivenNames: "Marianne",
    instruments: "Solistin Stimmlage Mezzosopran\"  \"",
    conductorLastName: "Nagano",
    conductorGivenNames: "Kent",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-12 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Phantasy Quartet on British Folkssongs, op. 36; Streichquartett e-Moll; 5 Fantasias in 4 Parts; Phantasy Quartet",
    title: "1. Kammerkonzert \u00bbPhantasy\u00ab",
    composers: "Holst; Smyth; Purcell",
    composerGivenNames: "Gustav; Dame Ethel Mary; Henry; Imogen",
    titles: "1. Kammerkonzert \u00bbPhantasy\u00ab",
    duration: "00:00:00",
    soloistsLastNames: "Hausdorf; Fordham; Shevlin; Eichler",
    soloistsGivenNames: "David; Simon Michael; Julian Peter; Valentin",
    instruments: "Violoncello; 2. Violine; 1. Violine; Bratsche",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-18 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "Fanfare Ritmico; Konzert f\u00fcr Klavier F-Dur; Sinfonie Nr.3",
    title: "Klangwelten der Gegenwart",
    composers: "Higdon; Gershwin; Copland",
    composerGivenNames: "Jennifer; George; Aaron",
    titles: "Klangwelten der Gegenwart",
    duration: "01:18:00",
    soloistsLastNames: "Buchbinder",
    soloistsGivenNames: "Rudolf",
    instruments: "Solopianist/ in",
    conductorLastName: "Macelaru",
    conductorGivenNames: "Cristian",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-19 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "Sinfonie Nr.3; Fanfare Ritmico; Konzert f\u00fcr Klavier F-Dur",
    title: "Klangwelten der Gegenwart",
    composers: "Copland; Higdon; Gershwin",
    composerGivenNames: "Aaron; Jennifer; George",
    titles: "Klangwelten der Gegenwart",
    duration: "01:18:00",
    soloistsLastNames: "Buchbinder",
    soloistsGivenNames: "Rudolf",
    instruments: "Solopianist/ in",
    conductorLastName: "Macelaru",
    conductorGivenNames: "Cristian",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-24 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "Sinfonia; Images - 1.Gigues; Images - 2.Ib\u00e9ria; Images - 3.Rondes des printemps",
    title: "100. Geburtstage (Berio)",
    composers: "Berio; Debussy",
    composerGivenNames: "Luciano; Claude",
    titles: "100. Geburtstage (Berio)",
    duration: "01:46:00",
    soloistsLastNames: "B\u00fcrgi; Cantando Admont",
    soloistsGivenNames: "Cordula",
    instruments: "Leiter eines fremden Chores; Ensemble /Solistengruppe",
    conductorLastName: "Pintscher",
    conductorGivenNames: "Matthias",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-25 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "G4; F",
    programm: "Images - 3.Rondes des printemps; Sinfonia; Images - 1.Gigues; Images - 2.Ib\u00e9ria",
    title: "100. Geburtstage (Berio)",
    composers: "Debussy; Berio",
    composerGivenNames: "Claude; Luciano",
    titles: "100. Geburtstage (Berio)",
    duration: "03:32:00",
    soloistsLastNames: "B\u00fcrgi; Cantando Admont",
    soloistsGivenNames: "Cordula",
    instruments: "Leiter eines fremden Chores; Ensemble /Solistengruppe",
    conductorLastName: "Pintscher",
    conductorGivenNames: "Matthias",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-29 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "Missa pro defunctis; Sound and Fury; Rendering f\u00fcr Orchester",
    title: "Meister der Innovation",
    composers: "Haydn; Clyne; Schubert",
    composerGivenNames: "Michael; Anna; Franz",
    titles: "Meister der Innovation",
    duration: "04:35:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Tilling; Foster-Williams; Puskarz Thomas; Maqungo",
    soloistsGivenNames: "Camilla; Andrew; Xenia; Siyabonga",
    instruments: "Chor; Solistin Stimmlage Sopran\"   \"; Solist Stimmlage Bass\"   \"; Solistin Stimmlage Mezzosopran\"  \"; Solist Stimmlage Tenor\"  \"",
    conductorLastName: "Minasi",
    conductorGivenNames: "Ricardo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-10-30 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "Missa pro defunctis; Sound and Fury; Rendering f\u00fcr Orchester",
    title: "Meister der Innovation",
    composers: "Haydn; Clyne; Schubert",
    composerGivenNames: "Michael; Anna; Franz",
    titles: "Meister der Innovation",
    duration: "04:35:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Tilling; Foster-Williams; Puskarz Thomas; Maqungo",
    soloistsGivenNames: "Camilla; Andrew; Xenia; Siyabonga",
    instruments: "Chor; Solistin Stimmlage Sopran\"   \"; Solist Stimmlage Bass\"   \"; Solistin Stimmlage Mezzosopran\"  \"; Solist Stimmlage Tenor\"  \"",
    conductorLastName: "Minasi",
    conductorGivenNames: "Ricardo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-11-02 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Don Giovanni - eine Oper im Taschenformat",
    title: "2. Kammerkonzert \u00bbDon Giovanni\u00ab",
    composers: "Mozart",
    composerGivenNames: "Wolfgang Amadeus",
    titles: "2. Kammerkonzert \u00bbDon Giovanni\u00ab",
    duration: "00:00:00",
    soloistsLastNames: "Kofler; Courtin; Sigl; M\u00fcller; Kasparek",
    soloistsGivenNames: "Michael Martin; Cl\u00e9ment Pierre Marie; Burkhard Johannes Friedrich; Elisabeth Veronika; Gottfried Franz",
    instruments: "Fl\u00f6te; 2. Violine; Bratsche; Violoncello; Sprecher/-in",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-11-11 00:00:00",
    start: "09:30:00",
    type: "Kindergartenkonzert",
    venue: "Saal X - HP8",
    city: "M\u00fcnchen",
    series: null,
    programm: null,
    title: null,
    composers: null,
    composerGivenNames: null,
    titles: null,
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 200,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-11-14 00:00:00",
    start: "18:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "Jugendkonzert",
    programm: "Klavierkonzert Nr. 2; Sinfonie Nr.2 h-moll; Moscow Cheryomushki: Suite (1.-3. Satz)",
    title: "1. Jugendkonzert",
    composers: "Rachmaninoff; Borodin; Schostakowitsch",
    composerGivenNames: "Sergei; Alexander; Dmitrij",
    titles: "1. Jugendkonzert",
    duration: "01:16:00",
    soloistsLastNames: "Gerstein",
    soloistsGivenNames: "Kirill",
    instruments: "Solopianist/ in",
    conductorLastName: "Rouvali",
    conductorGivenNames: "Santtu-Matias",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-11-15 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "K4",
    programm: "Moscow Cheryomushki: Suite (1.-3. Satz); Klavierkonzert Nr. 2; Sinfonie Nr.2 h-moll",
    title: "Abo-Konzert",
    composers: "Schostakowitsch; Rachmaninoff; Borodin",
    composerGivenNames: "Dmitrij; Sergei; Alexander",
    titles: "Abo-Konzert",
    duration: "01:16:00",
    soloistsLastNames: "Gerstein",
    soloistsGivenNames: "Kirill",
    instruments: "Solopianist/ in",
    conductorLastName: "Rouvali",
    conductorGivenNames: "Santtu-Matias",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-11-16 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "Klavierkonzert Nr. 2; Sinfonie Nr.2 h-moll; Moscow Cheryomushki: Suite (1.-3. Satz)",
    title: "Matinee",
    composers: "Rachmaninoff; Borodin; Schostakowitsch",
    composerGivenNames: "Sergei; Alexander; Dmitrij",
    titles: "Matinee",
    duration: "01:16:00",
    soloistsLastNames: "Gerstein",
    soloistsGivenNames: "Kirill",
    instruments: "Solopianist/ in",
    conductorLastName: "Rouvali",
    conductorGivenNames: "Santtu-Matias",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-11-20 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "Konzert f\u00fcr 2 Klaviere; Sinfonie Nr.4; Die Hebriden (oder Die Fingalsh\u00f6hle\")  \"",
    title: "Mendelssohn & Tschaikowsky",
    composers: "Mendelssohn-Bartholdy; Tschaikowsky",
    composerGivenNames: "Felix; Piotr Ilyich",
    titles: "Mendelssohn & Tschaikowsky",
    duration: "01:52:00",
    soloistsLastNames: "Jussen",
    soloistsGivenNames: "Arthur; Lucas",
    instruments: "Solopianist/ in",
    conductorLastName: "Sokhiev",
    conductorGivenNames: "Tugan",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-11-21 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "Jugendkonzert",
    programm: "Konzert f\u00fcr 2 Klaviere; Sinfonie Nr.4; Die Hebriden (oder Die Fingalsh\u00f6hle\")  \"",
    title: "Uni/U30-Spezial",
    composers: "Mendelssohn-Bartholdy; Tschaikowsky",
    composerGivenNames: "Felix; Piotr Ilyich",
    titles: "Uni/U30-Spezial",
    duration: "01:52:00",
    soloistsLastNames: "Jussen",
    soloistsGivenNames: "Arthur; Lucas",
    instruments: "Solopianist/ in",
    conductorLastName: "Sokhiev",
    conductorGivenNames: "Tugan",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-11-22 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "Konzert f\u00fcr 2 Klaviere; Sinfonie Nr.4; Die Hebriden (oder Die Fingalsh\u00f6hle\")  \"",
    title: "Abo-Wiederholung",
    composers: "Mendelssohn-Bartholdy; Tschaikowsky",
    composerGivenNames: "Felix; Piotr Ilyich",
    titles: "Abo-Wiederholung",
    duration: "01:52:00",
    soloistsLastNames: "Jussen",
    soloistsGivenNames: "Arthur; Lucas",
    instruments: "Solopianist/ in",
    conductorLastName: "Sokhiev",
    conductorGivenNames: "Tugan",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-05 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "Sinfonie Nr.4 B-Dur; Arpeggione; Wilhelm Tell: Ouvert\u00fcre",
    title: "Klangwelten der Gegenwart",
    composers: "Beethoven; Schubert; Rossini",
    composerGivenNames: "Ludwig van; Franz; Gioacchino",
    titles: "Klangwelten der Gegenwart",
    duration: "01:14:00",
    soloistsLastNames: "Kobekina",
    soloistsGivenNames: "Anastasia",
    instruments: "Violoncello",
    conductorLastName: "Chang",
    conductorGivenNames: "Han-Na",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-06 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "E4",
    programm: "Sinfonie Nr.4 B-Dur; Arpeggione; Wilhelm Tell: Ouvert\u00fcre",
    title: "Rossini / Schubert / Beethoven",
    composers: "Beethoven; Schubert; Rossini",
    composerGivenNames: "Ludwig van; Franz; Gioacchino",
    titles: "Rossini / Schubert / Beethoven",
    duration: "01:14:00",
    soloistsLastNames: "Kobekina",
    soloistsGivenNames: "Anastasia",
    instruments: "Violoncello",
    conductorLastName: "Chang",
    conductorGivenNames: "Han-Na",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-10 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "El sombrero de tres picos - Suite Nr. 1; El sombrero de tres picos - Suite Nr. 2; Altar de Cuerda (Violinkonzert); Bolero; Danz\u00f3n Nr. 8",
    title: "Klangwelten (Repeat)",
    composers: "Falla; Ortiz; Ravel; Marquez",
    composerGivenNames: "Manuel de; Gabriela; Maurice; Arturo",
    titles: "Klangwelten (Repeat)",
    duration: "01:14:00",
    soloistsLastNames: "Due\u00f1as",
    soloistsGivenNames: "Maria",
    instruments: "Violine",
    conductorLastName: "Bortolameolli",
    conductorGivenNames: "Paolo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-11 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "Altar de Cuerda (Violinkonzert); Bolero; Danz\u00f3n Nr. 8; El sombrero de tres picos - Suite Nr. 1; El sombrero de tres picos - Suite Nr. 2",
    title: "Klangwelten (Repeat)",
    composers: "Ortiz; Ravel; Marquez; Falla",
    composerGivenNames: "Gabriela; Maurice; Arturo; Manuel de",
    titles: "Klangwelten (Repeat)",
    duration: "01:14:00",
    soloistsLastNames: "Due\u00f1as",
    soloistsGivenNames: "Maria",
    instruments: "Violine",
    conductorLastName: "Bortolameolli",
    conductorGivenNames: "Paolo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-12 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "F; G4",
    programm: "Altar de Cuerda (Violinkonzert); Bolero; Danz\u00f3n Nr. 8; El sombrero de tres picos - Suite Nr. 1; El sombrero de tres picos - Suite Nr. 2",
    title: "Klangwelten (Repeat)",
    composers: "Ortiz; Ravel; Marquez; Falla",
    composerGivenNames: "Gabriela; Maurice; Arturo; Manuel de",
    titles: "Klangwelten (Repeat)",
    duration: "02:28:00",
    soloistsLastNames: "Due\u00f1as",
    soloistsGivenNames: "Maria",
    instruments: "Violine",
    conductorLastName: "Bortolameolli",
    conductorGivenNames: "Paolo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-14 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Nocturne and Scherzo; Streichtrio op. 19; Phantasy Quintet; Streichtrio D-Dur op. 6",
    title: "3. Kammerkonzert \u00bbVery British\u00ab",
    composers: "Vaughan Williams; Berkeley; Smyth",
    composerGivenNames: "Ralph; Lennox; Dame Ethel Mary",
    titles: "3. Kammerkonzert \u00bbVery British\u00ab",
    duration: "00:00:00",
    soloistsLastNames: "Tolpygo; Rieke; Risbet; Wohlgemuth; Shevlin",
    soloistsGivenNames: "Vladimir; Jannis Michael; Julie Amandine Laure; Joachim Eckart; Julian Peter",
    instruments: "1. Violine; Bratsche; Violoncello",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-17 00:00:00",
    start: "09:30:00",
    type: "Kindergartenkonzert",
    venue: "Saal X - HP8",
    city: "M\u00fcnchen",
    series: null,
    programm: null,
    title: null,
    composers: null,
    composerGivenNames: null,
    titles: null,
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 200,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-19 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "K4",
    programm: "Evening Hymn; Konzert in D-Dur f\u00fcr Trompete und Orchester; Sonata pian e forte; Psalmensymphonie; Sinfonie Nr.92 (Oxford\")   \"",
    title: "Advent & Psalmen",
    composers: "Gardiner; Tartini; Gabrieli; Strawinsky; Haydn",
    composerGivenNames: "Henry Balfour; Giuseppe; Giovanni; Igor; Joseph",
    titles: "Advent & Psalmen",
    duration: "01:05:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Segers",
    soloistsGivenNames: "Guido Lambertus",
    instruments: "Chor; Trompete",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-20 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "Psalmensymphonie; Sinfonie Nr.92 (Oxford\")   \"; Evening Hymn; Konzert in D-Dur f\u00fcr Trompete und Orchester; Sonata pian e forte",
    title: "Advent & Psalmen",
    composers: "Strawinsky; Haydn; Gardiner; Tartini; Gabrieli",
    composerGivenNames: "Igor; Joseph; Henry Balfour; Giuseppe; Giovanni",
    titles: "Advent & Psalmen",
    duration: "01:05:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Segers",
    soloistsGivenNames: "Guido Lambertus",
    instruments: "Chor; Trompete",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-21 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "Psalmensymphonie; Sinfonie Nr.92 (Oxford\")   \"; Evening Hymn; Konzert in D-Dur f\u00fcr Trompete und Orchester; Sonata pian e forte",
    title: "Advent & Psalmen (Matinee)",
    composers: "Strawinsky; Haydn; Gardiner; Tartini; Gabrieli",
    composerGivenNames: "Igor; Joseph; Henry Balfour; Giuseppe; Giovanni",
    titles: "Advent & Psalmen (Matinee)",
    duration: "01:05:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Segers",
    soloistsGivenNames: "Guido Lambertus",
    instruments: "Chor; Trompete",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-30 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "H4",
    programm: "Sinfonie Nr.9 d-moll",
    title: "Beethoven 9 (Silvester)",
    composers: "Beethoven",
    composerGivenNames: "Ludwig van",
    titles: "Beethoven 9 (Silvester)",
    duration: "05:25:00",
    soloistsLastNames: "Romero; Kristinnson; Kissjudit; Takala; Philharmonischer Chor M\u00fcnchen",
    soloistsGivenNames: "Angel; Johann; Anna; Tuuli",
    instruments: "Solist Stimmlage Tenor\"  \"; Solist Stimmlage Bassbariton\"  \"; Solistin Stimmlage Mezzosopran\"  \"; Solistin Stimmlage Sopran\"   \"; Chor",
    conductorLastName: "Ollikainen",
    conductorGivenNames: "Eva",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2025-12-31 00:00:00",
    start: "17:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: null,
    programm: "Sinfonie Nr.9 d-moll",
    title: "Beethoven 9 (Silvester)",
    composers: "Beethoven",
    composerGivenNames: "Ludwig van",
    titles: "Beethoven 9 (Silvester)",
    duration: "05:25:00",
    soloistsLastNames: "Romero; Kristinnson; Kissjudit; Takala; Philharmonischer Chor M\u00fcnchen",
    soloistsGivenNames: "Angel; Johann; Anna; Tuuli",
    instruments: "Solist Stimmlage Tenor\"  \"; Solist Stimmlage Bassbariton\"  \"; Solistin Stimmlage Mezzosopran\"  \"; Solistin Stimmlage Sopran\"   \"; Chor",
    conductorLastName: "Ollikainen",
    conductorGivenNames: "Eva",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-09 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "Exsultate jubilate; Sinfonie Nr.39 Es-Dur; Sinfonie Nr.34; Die Hochzeit des Figaro - Ouvert\u00fcre; Cosi fan tutte - Ei parte..senti..ah no!\"  \"; Il re pastore : L'amer\u00f2, sar\u00f2 costante\"  \"; La clemenza di tito: Parto, ma tu, ben mio\"  \"",
    title: "Mozart-Gala",
    composers: "Mozart",
    composerGivenNames: "Wolfgang Amadeus",
    titles: "Mozart-Gala",
    duration: "01:26:00",
    soloistsLastNames: "Lezhneva",
    soloistsGivenNames: "Julia",
    instruments: "Solistin Stimmlage Sopran\"   \"",
    conductorLastName: "Marcon",
    conductorGivenNames: "Andrea",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-10 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "Die Hochzeit des Figaro - Ouvert\u00fcre; Cosi fan tutte - Ei parte..senti..ah no!\"  \"; Il re pastore : L'amer\u00f2, sar\u00f2 costante\"  \"; La clemenza di tito: Parto, ma tu, ben mio\"  \"; Exsultate jubilate; Sinfonie Nr.39 Es-Dur; Sinfonie Nr.34",
    title: "Mozart-Gala",
    composers: "Mozart",
    composerGivenNames: "Wolfgang Amadeus",
    titles: "Mozart-Gala",
    duration: "01:26:00",
    soloistsLastNames: "Lezhneva",
    soloistsGivenNames: "Julia",
    instruments: "Solistin Stimmlage Sopran\"   \"",
    conductorLastName: "Marcon",
    conductorGivenNames: "Andrea",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-16 00:00:00",
    start: "10:00:00",
    type: "Kinderkonzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: null,
    programm: "Der Schneemann; Schauspiel-Ouvert\u00fcre",
    title: "Kinderkonzert Der Schneemann",
    composers: "Korngold",
    composerGivenNames: "Erich",
    titles: "Kinderkonzert Der Schneemann",
    duration: "03:40:00",
    soloistsLastNames: "Koerselman; Schausberger; Hackspiel; Bufe",
    soloistsGivenNames: "Annechien; Angela; Florian; B\u00e9la",
    instruments: "Regisseur; Schauspieler/in",
    conductorLastName: "Venzago",
    conductorGivenNames: "Gabriel",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-16 00:00:00",
    start: "15:00:00",
    type: "Kinderkonzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: null,
    programm: "Der Schneemann; Schauspiel-Ouvert\u00fcre",
    title: "Familienkonzert Der Schneemann",
    composers: "Korngold",
    composerGivenNames: "Erich",
    titles: "Familienkonzert Der Schneemann",
    duration: "03:40:00",
    soloistsLastNames: "Koerselman; Schausberger; Hackspiel; Bufe",
    soloistsGivenNames: "Annechien; Angela; Florian; B\u00e9la",
    instruments: "Regisseur; Schauspieler/in",
    conductorLastName: "Venzago",
    conductorGivenNames: "Gabriel",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-18 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Zodiac / Tierkreis; Streich-Quintett G-Dur op. 77; Suite Espagnole",
    title: "4. Kammerkonzert \u00bbDurch Raum und Zeit\u00ab",
    composers: "Stockhausen; Dvorak; Albeniz",
    composerGivenNames: "Karlheinz; Antonin; Isaac",
    titles: "4. Kammerkonzert \u00bbDurch Raum und Zeit\u00ab",
    duration: "00:00:00",
    soloistsLastNames: "Schwarzfischer; Risbet; Margasyuk; von der Nahmer; Schmitz; von Neumann-Cosel; Gruber; Giannotti",
    soloistsGivenNames: "Mia; Julie Amandine Laure; Victoria; Manuel; Katharina; Ulrich Vitus; Alexandra Maria; Raffaele",
    instruments: "Horn; Bratsche; 1. Violine; Violoncello; 2. Violine; Kontraba\u00df; Klarinette; Fagott",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-21 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "Devotion; Sinfonische Ballade f\u00fcr Cello und Orchester; Fancy Free; Kinah",
    title: "Hollywood & Broadway",
    composers: "Korngold; Mackeben; Bernstein; Slatkin",
    composerGivenNames: "Erich; Theo; Leonard",
    titles: "Hollywood & Broadway",
    duration: "01:10:00",
    soloistsLastNames: "Mijnders",
    soloistsGivenNames: "Floris",
    instruments: "Violoncello",
    conductorLastName: "Marshall",
    conductorGivenNames: "Wayne",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-22 00:00:00",
    start: "18:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "Jugendkonzert",
    programm: "Sinfonische Ballade f\u00fcr Cello und Orchester; Fancy Free; Devotion",
    title: "2. Jugendkonzert Hollywood & Broadway",
    composers: "Mackeben; Bernstein; Korngold",
    composerGivenNames: "Theo; Leonard; Erich",
    titles: "2. Jugendkonzert Hollywood & Broadway",
    duration: "00:57:00",
    soloistsLastNames: "Mijnders",
    soloistsGivenNames: "Floris",
    instruments: "Violoncello",
    conductorLastName: "Marshall",
    conductorGivenNames: "Wayne",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-23 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "K4",
    programm: "Devotion; Sinfonische Ballade f\u00fcr Cello und Orchester; Fancy Free; Kinah",
    title: "Hollywood & Broadway",
    composers: "Korngold; Mackeben; Bernstein; Slatkin",
    composerGivenNames: "Erich; Theo; Leonard",
    titles: "Hollywood & Broadway",
    duration: "01:10:00",
    soloistsLastNames: "Mijnders",
    soloistsGivenNames: "Floris",
    instruments: "Violoncello",
    conductorLastName: "Marshall",
    conductorGivenNames: "Wayne",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-28 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "F; I",
    programm: "Pell\u00e9as und M\u00e9lisande; Klavierkonzert Nr.27; Pr\u00e9lude \u00e0 l'apr\u00e8s-midi d'un faune",
    title: "Debussy / Mozart / Sch\u00f6nberg",
    composers: "Sch\u00f6nberg; Mozart; Debussy",
    composerGivenNames: "Arnold; Wolfgang Amadeus; Claude",
    titles: "Debussy / Mozart / Sch\u00f6nberg",
    duration: "02:42:00",
    soloistsLastNames: "Shani",
    soloistsGivenNames: "Lahav",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-29 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "Pell\u00e9as und M\u00e9lisande; Klavierkonzert Nr.27; Pr\u00e9lude \u00e0 l'apr\u00e8s-midi d'un faune",
    title: "Debussy / Mozart / Sch\u00f6nberg",
    composers: "Sch\u00f6nberg; Mozart; Debussy",
    composerGivenNames: "Arnold; Wolfgang Amadeus; Claude",
    titles: "Debussy / Mozart / Sch\u00f6nberg",
    duration: "01:21:00",
    soloistsLastNames: "Shani",
    soloistsGivenNames: "Lahav",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-01-30 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "Pell\u00e9as und M\u00e9lisande; Klavierkonzert Nr.27; Pr\u00e9lude \u00e0 l'apr\u00e8s-midi d'un faune",
    title: "Debussy / Mozart / Sch\u00f6nberg",
    composers: "Sch\u00f6nberg; Mozart; Debussy",
    composerGivenNames: "Arnold; Wolfgang Amadeus; Claude",
    titles: "Debussy / Mozart / Sch\u00f6nberg",
    duration: "01:21:00",
    soloistsLastNames: "Shani",
    soloistsGivenNames: "Lahav",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-02-11 00:00:00",
    start: "09:30:00",
    type: "Kindergartenkonzert",
    venue: "Saal X - HP8",
    city: "M\u00fcnchen",
    series: null,
    programm: null,
    title: null,
    composers: null,
    composerGivenNames: null,
    titles: null,
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 200,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-02-14 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "Music for Ensemble and Orchestra; Violinkonzert; Harmonium f\u00fcr Chor und Orchester",
    title: "Minimal meets Big Sound",
    composers: "Reich; Knussen; Adams",
    composerGivenNames: "Steve; Oliver; John",
    titles: "Minimal meets Big Sound",
    duration: "01:09:00",
    soloistsLastNames: "Josefowicz; Philharmonischer Chor M\u00fcnchen",
    soloistsGivenNames: "Leila",
    instruments: "Solist /-in Violine\"   \"; Chor",
    conductorLastName: "Lubman",
    conductorGivenNames: "Brad",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-02-15 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "Music for Ensemble and Orchestra; Violinkonzert; Harmonium f\u00fcr Chor und Orchester",
    title: "Minimal meets Big Sound (Matinee)",
    composers: "Reich; Knussen; Adams",
    composerGivenNames: "Steve; Oliver; John",
    titles: "Minimal meets Big Sound (Matinee)",
    duration: "01:09:00",
    soloistsLastNames: "Josefowicz; Philharmonischer Chor M\u00fcnchen",
    soloistsGivenNames: "Leila",
    instruments: "Solist /-in Violine\"   \"; Chor",
    conductorLastName: "Lubman",
    conductorGivenNames: "Brad",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-02-22 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Fl\u00f6tenquartett KV 285; Quintett f\u00fcr Fl\u00f6te, Harfe und Streichtrio; Deux Interludes; Elegiac Trio; Serenade",
    title: "5. Kammerkonzert \u00bbNordwest-Wind\u00ab",
    composers: "Mozart; Cras; Ibert; Bax; Roussel",
    composerGivenNames: "Wolfgang Amadeus; Jean; Jacques; Arnold; Albert",
    titles: "5. Kammerkonzert \u00bbNordwest-Wind\u00ab",
    duration: "00:00:00",
    soloistsLastNames: "Sigl; Arnholdt; Belic; Zimmermann; Okaya",
    soloistsGivenNames: "Burkhard Johannes Friedrich; Friederike Luise; Martin; Teresa Katharina; Megumi",
    instruments: "Bratsche; Violoncello; Fl\u00f6te; Harfe; 1. Violine",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-02-25 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "Klavierkonzert Nr.2 B-Dur; Blossoming II; Sinfonie Nr.2 D-Dur",
    title: null,
    composers: "Brahms; Hosokawa; Beethoven",
    composerGivenNames: "Johannes; Toshio; Ludwig van",
    titles: null,
    duration: "01:28:00",
    soloistsLastNames: "Levit",
    soloistsGivenNames: "Igor",
    instruments: "Solopianist/ in",
    conductorLastName: "Manacorda",
    conductorGivenNames: "Antonello",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-02-26 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "Klavierkonzert Nr.2 B-Dur; Blossoming II; Sinfonie Nr.2 D-Dur",
    title: null,
    composers: "Brahms; Hosokawa; Beethoven",
    composerGivenNames: "Johannes; Toshio; Ludwig van",
    titles: null,
    duration: "01:28:00",
    soloistsLastNames: "Levit",
    soloistsGivenNames: "Igor",
    instruments: "Solopianist/ in",
    conductorLastName: "Manacorda",
    conductorGivenNames: "Antonello",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-02-27 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "E4",
    programm: "Klavierkonzert Nr.2 B-Dur; Blossoming II; Sinfonie Nr.2 D-Dur",
    title: null,
    composers: "Brahms; Hosokawa; Beethoven",
    composerGivenNames: "Johannes; Toshio; Ludwig van",
    titles: null,
    duration: "01:28:00",
    soloistsLastNames: "Levit",
    soloistsGivenNames: "Igor",
    instruments: "Solopianist/ in",
    conductorLastName: "Manacorda",
    conductorGivenNames: "Antonello",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-06 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "The dream of Gerontius",
    title: "Englische Musik III",
    composers: "Elgar",
    composerGivenNames: "Edward",
    titles: "Englische Musik III",
    duration: "06:40:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Foster-Williams; Taylor; Staples",
    soloistsGivenNames: "Andrew; Beth",
    instruments: "Chor; Solist Stimmlage Bass\"   \"; Solistin Stimmlage Mezzosopran\"  \"; Solist Stimmlage Tenor\"  \"",
    conductorLastName: "Manze",
    conductorGivenNames: "Andrew",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-07 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "I; F",
    programm: "The dream of Gerontius",
    title: "Englische Musik III",
    composers: "Elgar",
    composerGivenNames: "Edward",
    titles: "Englische Musik III",
    duration: "13:20:00",
    soloistsLastNames: "Staples; Philharmonischer Chor M\u00fcnchen; Foster-Williams; Taylor",
    soloistsGivenNames: "Andrew; Beth",
    instruments: "Solist Stimmlage Tenor\"  \"; Chor; Solist Stimmlage Bass\"   \"; Solistin Stimmlage Mezzosopran\"  \"",
    conductorLastName: "Manze",
    conductorGivenNames: "Andrew",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-11 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "Sinfonie Nr.4; Klavierkonzert Nr.2 B-Dur",
    title: "Beethoven Kb 2 \u00b7 Brahms 4",
    composers: "Brahms; Beethoven",
    composerGivenNames: "Johannes; Ludwig van",
    titles: "Beethoven Kb 2 \u00b7 Brahms 4",
    duration: "01:10:00",
    soloistsLastNames: "Buchbinder",
    soloistsGivenNames: "Rudolf",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-12 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "H4",
    programm: "Sinfonie Nr.4; Klavierkonzert Nr.2 B-Dur",
    title: "Beethoven Kb 2 \u00b7 Brahms 4",
    composers: "Brahms; Beethoven",
    composerGivenNames: "Johannes; Ludwig van",
    titles: "Beethoven Kb 2 \u00b7 Brahms 4",
    duration: "01:10:00",
    soloistsLastNames: "Buchbinder",
    soloistsGivenNames: "Rudolf",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-15 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Klavierquintett Nr. 1 a-Moll op. 30; Klavierquintett c-Moll",
    title: "6. Kammerkonzert \u00bbTiefgr\u00fcndig",
    composers: "Farrenc; Vaughan Williams",
    composerGivenNames: "Louise; Ralph",
    titles: "6. Kammerkonzert \u00bbTiefgr\u00fcndig",
    duration: "02:30:00",
    soloistsLastNames: "Neumann; Fordham; Springorum; M\u00fcller; Rivinius",
    soloistsGivenNames: "Michael; Simon Michael; Beate; Elisabeth Veronika; Paul Konstantin",
    instruments: "Kontraba\u00df; 2. Violine; Bratsche; Violoncello; Solopianist/ in",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-22 00:00:00",
    start: "11:00:00",
    type: "Familienkonzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: null,
    programm: "Senta und die verfluchte Partitur",
    title: null,
    composers: "Janosa",
    composerGivenNames: "Felix",
    titles: null,
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: "N.N.",
    conductorGivenNames: null,
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-22 00:00:00",
    start: "15:00:00",
    type: "Familienkonzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: null,
    programm: "Senta und die verfluchte Partitur",
    title: "Familienmusical Senta (Jubil\u00e4um)",
    composers: "Janosa",
    composerGivenNames: "Felix",
    titles: "Familienmusical Senta (Jubil\u00e4um)",
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: "N.N.",
    conductorGivenNames: null,
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-23 00:00:00",
    start: "10:00:00",
    type: "Schulkonzerte",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: null,
    programm: "Senta und die verfluchte Partitur",
    title: "Schulvorstellung Senta",
    composers: "Janosa",
    composerGivenNames: "Felix",
    titles: "Schulvorstellung Senta",
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: "N.N.",
    conductorGivenNames: null,
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-28 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "Swaddling Silk and Gossamer Rain; Violinkonzert D-Dur; Enigma variations",
    title: null,
    composers: "Koide; Tschaikowsky; Elgar",
    composerGivenNames: "Noriko; Piotr Ilyich; Edward",
    titles: null,
    duration: "01:19:00",
    soloistsLastNames: "Hadelich",
    soloistsGivenNames: "Augustin",
    instruments: "Solist /-in Violine\"   \"",
    conductorLastName: "Chan",
    conductorGivenNames: "Elim",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-03-29 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "Swaddling Silk and Gossamer Rain; Violinkonzert D-Dur; Enigma variations",
    title: "MABO-Matinee",
    composers: "Koide; Tschaikowsky; Elgar",
    composerGivenNames: "Noriko; Piotr Ilyich; Edward",
    titles: "MABO-Matinee",
    duration: "01:19:00",
    soloistsLastNames: "Hadelich",
    soloistsGivenNames: "Augustin",
    instruments: "Solist /-in Violine\"   \"",
    conductorLastName: "Chan",
    conductorGivenNames: "Elim",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-04-17 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "Sinfonie Nr.7 A-Dur; L'apoth\u00e9ose de la Danse\"   \"",
    title: "Meister der Innovation III",
    composers: "Beethoven; Rameau",
    composerGivenNames: "Ludwig van; Jean-Philippe",
    titles: "Meister der Innovation III",
    duration: "01:17:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: "Pichon",
    conductorGivenNames: "Raphael",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-04-18 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "L'apoth\u00e9ose de la Danse\"   \"; Sinfonie Nr.7 A-Dur",
    title: null,
    composers: "Rameau; Beethoven",
    composerGivenNames: "Jean-Philippe; Ludwig van",
    titles: null,
    duration: "01:17:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: "Pichon",
    conductorGivenNames: "Raphael",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-04-19 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Variationen \u00fcber Nango ti deo\"   \"; Serenade f\u00fcr Streichtrio C-Dur KV 648; Streichquartett F-Dur KV 590; Omar; Camino pro vereda",
    title: null,
    composers: "Campo; Mozart; Alyamani",
    composerGivenNames: "Jenny Pe\u00f1a; Wolfgang Amadeus; MAias",
    titles: null,
    duration: "00:00:00",
    soloistsLastNames: "von der Nahmer; Courtin; Metz; Sellheim",
    soloistsGivenNames: "Manuel; Cl\u00e9ment Pierre Marie; Georg Bernhard; Konstantin Alexander",
    instruments: "Violoncello; 2. Violine; Bratsche",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-04-23 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "Sinfonie Nr.1; Klavierkonzert Nr.1 C-Dur",
    title: "Beethoven Kb 1 \u00b7 Mahler 1",
    composers: "Mahler; Beethoven",
    composerGivenNames: "Gustav; Ludwig van",
    titles: "Beethoven Kb 1 \u00b7 Mahler 1",
    duration: "01:26:00",
    soloistsLastNames: "Cho",
    soloistsGivenNames: "Seong-Jin",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-04-24 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "F; G4",
    programm: "Klavierkonzert Nr.1 C-Dur; Sinfonie Nr.1",
    title: "Beethoven Kb 1 \u00b7 Mahler 1",
    composers: "Beethoven; Mahler",
    composerGivenNames: "Ludwig van; Gustav",
    titles: "Beethoven Kb 1 \u00b7 Mahler 1",
    duration: "02:52:00",
    soloistsLastNames: "Cho",
    soloistsGivenNames: "Seong-Jin",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-04-27 00:00:00",
    start: "18:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "Jugendkonzert",
    programm: "Klavierkonzert Nr. 2; Don Juan",
    title: null,
    composers: "Prokofieff; Strauss",
    composerGivenNames: "Sergej; Richard",
    titles: null,
    duration: "00:48:00",
    soloistsLastNames: "Cho",
    soloistsGivenNames: "Seong-Jin",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-05-20 00:00:00",
    start: "09:30:00",
    type: "Kindergartenkonzert",
    venue: "Saal X - HP8",
    city: "M\u00fcnchen",
    series: null,
    programm: null,
    title: null,
    composers: null,
    composerGivenNames: null,
    titles: null,
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 200,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-05-23 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "H4",
    programm: "Finlandia; Klavierkonzert Nr. 1; Sinfonie Nr.2 (London\")  \"",
    title: "Englische Musik IV",
    composers: "Sibelius; Rautavaara; Vaughan Williams",
    composerGivenNames: "Jean; Einojuhani; Ralph",
    titles: "Englische Musik IV",
    duration: "01:06:00",
    soloistsLastNames: "Wang",
    soloistsGivenNames: "Yuja",
    instruments: "Solopianist/ in",
    conductorLastName: "Peltokowski",
    conductorGivenNames: "Tarmo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-05-24 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "Finlandia; Klavierkonzert Nr. 1; Sinfonie Nr.2 (London\")  \"",
    title: null,
    composers: "Sibelius; Rautavaara; Vaughan Williams",
    composerGivenNames: "Jean; Einojuhani; Ralph",
    titles: null,
    duration: "01:06:00",
    soloistsLastNames: "Wang",
    soloistsGivenNames: "Yuja",
    instruments: "Solopianist/ in",
    conductorLastName: "Peltokowski",
    conductorGivenNames: "Tarmo",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-05-29 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "Klavierkonzert; L'Arl\u00e9sienne-Suite Nr.2; Khovantchina: Vorspiel zum 1. Akt; L'Arl\u00e9sienne-Suite Nr.1",
    title: "Altinoglu \u2013 Bizet u. a.",
    composers: "Khatchaturian; Bizet; Mussorgsky",
    composerGivenNames: "Aram; Georges; Modest",
    titles: "Altinoglu \u2013 Bizet u. a.",
    duration: "01:14:00",
    soloistsLastNames: "Gigashvili",
    soloistsGivenNames: "Giorgi",
    instruments: "Solopianist/ in",
    conductorLastName: "Altinoglu",
    conductorGivenNames: "Alain",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-05-30 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "F; I",
    programm: "Klavierkonzert; Khovantchina: Vorspiel zum 1. Akt; L'Arl\u00e9sienne-Suite Nr.1; L'Arl\u00e9sienne-Suite Nr.2",
    title: "Altinoglu \u2013 Bizet u. a.",
    composers: "Khatchaturian; Mussorgsky; Bizet",
    composerGivenNames: "Aram; Modest; Georges",
    titles: "Altinoglu \u2013 Bizet u. a.",
    duration: "02:28:00",
    soloistsLastNames: "Gigashvili",
    soloistsGivenNames: "Giorgi",
    instruments: "Solopianist/ in",
    conductorLastName: "Altinoglu",
    conductorGivenNames: "Alain",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-13 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "H4",
    programm: "Feldmesse; F\u00fcrst Igor: Polovetzer T\u00e4nze; Vier letzte Lieder; Adagietto aus der Sinfonie Nr.5",
    title: "Hr\u016f\u0161a \u2013 Mahler/ Strauss/ Martin\u016f",
    composers: "Martinu; Borodin; Strauss; Mahler",
    composerGivenNames: "Bohuslav; Alexander; Richard; Gustav",
    titles: "Hr\u016f\u0161a \u2013 Mahler/ Strauss/ Martin\u016f",
    duration: "01:39:00",
    soloistsLastNames: "Philharmonischer Chor M\u00fcnchen; Br\u00fcckler; Winters",
    soloistsGivenNames: "Jir\u00ed; Corinne",
    instruments: "Chor; Solist Stimmlage Bariton\"  \"; Solistin Stimmlage Sopran\"   \"",
    conductorLastName: "Hrusa",
    conductorGivenNames: "Jakub",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-14 00:00:00",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "M",
    programm: "Vier letzte Lieder; Adagietto aus der Sinfonie Nr.5; Feldmesse; F\u00fcrst Igor: Polovetzer T\u00e4nze",
    title: "Hr\u016f\u0161a \u2013 Mahler/ Strauss/ Martin\u016f (Matinee)",
    composers: "Strauss; Mahler; Martinu; Borodin",
    composerGivenNames: "Richard; Gustav; Bohuslav; Alexander",
    titles: "Hr\u016f\u0161a \u2013 Mahler/ Strauss/ Martin\u016f (Matinee)",
    duration: "01:39:00",
    soloistsLastNames: "Winters; Philharmonischer Chor M\u00fcnchen; Br\u00fcckler",
    soloistsGivenNames: "Corinne; Jir\u00ed",
    instruments: "Solistin Stimmlage Sopran\"   \"; Chor; Solist Stimmlage Bariton\"  \"",
    conductorLastName: "Hrusa",
    conductorGivenNames: "Jakub",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-14 00:00:00",
    start: "17:00:00",
    type: "Konzert",
    venue: "Halle E",
    city: "M\u00fcnchen",
    series: null,
    programm: null,
    title: "Symphonic Mob",
    composers: null,
    composerGivenNames: null,
    titles: "Symphonic Mob",
    duration: "00:00:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 0,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-18 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "B",
    programm: "Klarinettenkonzert A-Dur; Sinfonie Nr.9",
    title: "Mehta \u2013 Mozart KlarinettK + Bruckner 9",
    composers: "Mozart; Bruckner",
    composerGivenNames: "Wolfgang Amadeus; Anton",
    titles: "Mehta \u2013 Mozart KlarinettK + Bruckner 9",
    duration: "01:28:00",
    soloistsLastNames: "Gruber",
    soloistsGivenNames: "Alexandra Maria",
    instruments: "Klarinette",
    conductorLastName: "Mehta",
    conductorGivenNames: "Zubin",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-19 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "E4",
    programm: "Klarinettenkonzert A-Dur; Sinfonie Nr.9",
    title: "Mehta \u2013 Mozart KlarinettK + Bruckner 9",
    composers: "Mozart; Bruckner",
    composerGivenNames: "Wolfgang Amadeus; Anton",
    titles: "Mehta \u2013 Mozart KlarinettK + Bruckner 9",
    duration: "01:28:00",
    soloistsLastNames: "Gruber",
    soloistsGivenNames: "Alexandra Maria",
    instruments: "Klarinette",
    conductorLastName: "Mehta",
    conductorGivenNames: "Zubin",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-20 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "D",
    programm: "Klarinettenkonzert A-Dur; Sinfonie Nr.9",
    title: null,
    composers: "Mozart; Bruckner",
    composerGivenNames: "Wolfgang Amadeus; Anton",
    titles: null,
    duration: "01:28:00",
    soloistsLastNames: "Gruber",
    soloistsGivenNames: "Alexandra Maria",
    instruments: "Klarinette",
    conductorLastName: "Mehta",
    conductorGivenNames: "Zubin",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-21 00:00:00",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "M\u00fcnchner K\u00fcnstlerhaus",
    city: "M\u00fcnchen",
    series: null,
    programm: "Andante and Allegro; Divertimento f\u00fcr Oboenquintett C-Dur op. 9; Streichquartett Nr. 2; Oboenquartett F-Dur KV 370; Oboenquintett D-Dur op. 55 Nr. 3; Miniaturen",
    title: null,
    composers: "Elgar; Crusell; Schulhoff; Mozart; Boccherini; Cohen",
    composerGivenNames: "Edward; Bernhard Henrik; Erwin; Wolfgang Amadeus; Luigi; Ohad",
    titles: null,
    duration: "00:00:00",
    soloistsLastNames: "Funk-Hoever; Cohen; Schmitz; Rieke; Modersohn",
    soloistsGivenNames: "Elke; Ohad; Katharina; Jannis Michael; Marie-Luise",
    instruments: "Violoncello; 1. Violine; 2. Violine; Bratsche; Oboe",
    conductorLastName: null,
    conductorGivenNames: null,
    capacity: 400,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-24 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "A",
    programm: "Dance symphony; Sinfonie Nr.90; Ga\u00eet\u00e9 parisienne; Songs",
    title: "Abo-Konzert (TBA)",
    composers: "Copland; Haydn; Offenbach; Weill",
    composerGivenNames: "Aaron; Joseph; Jacques; Kurt",
    titles: "Abo-Konzert (TBA)",
    duration: "01:21:00",
    soloistsLastNames: "Hannigan",
    soloistsGivenNames: "Barbara",
    instruments: "Solistin Stimmlage Sopran\"   \"",
    conductorLastName: "Hannigan",
    conductorGivenNames: "Barbara",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-06-25 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "G4; F",
    programm: "Ga\u00eet\u00e9 parisienne; Songs; Dance symphony; Sinfonie Nr.90",
    title: "Wiederholung (TBA)",
    composers: "Offenbach; Weill; Copland; Haydn",
    composerGivenNames: "Jacques; Kurt; Aaron; Joseph",
    titles: "Wiederholung (TBA)",
    duration: "02:42:00",
    soloistsLastNames: "Hannigan",
    soloistsGivenNames: "Barbara",
    instruments: "Solistin Stimmlage Sopran\"   \"",
    conductorLastName: "Hannigan",
    conductorGivenNames: "Barbara",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-07-02 00:00:00",
    start: "18:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "Jugendkonzert",
    programm: "Konzert f\u00fcr Violine und Orchester; Feuervogel-Suite (Fassung: 1919)",
    title: "4. Jugendkonzert",
    composers: "Dvorak; Strawinsky",
    composerGivenNames: "Antonin; Igor",
    titles: "4. Jugendkonzert",
    duration: "00:53:00",
    soloistsLastNames: "Faust",
    soloistsGivenNames: "Isabelle",
    instruments: "Solist /-in Violine\"   \"",
    conductorLastName: "Popelka",
    conductorGivenNames: "Petr",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-07-03 00:00:00",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "C",
    programm: "Konzert f\u00fcr Violine und Orchester; Sebastian im Traum; Feuervogel-Suite (Fassung: 1919)",
    title: "Abo-Konzert",
    composers: "Dvorak; Henze; Strawinsky",
    composerGivenNames: "Antonin; Hans Werner; Igor",
    titles: "Abo-Konzert",
    duration: "01:08:00",
    soloistsLastNames: "Faust",
    soloistsGivenNames: "Isabelle",
    instruments: "Solist /-in Violine\"   \"",
    conductorLastName: "Popelka",
    conductorGivenNames: "Petr",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-07-04 00:00:00",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: "K4",
    programm: "Konzert f\u00fcr Violine und Orchester; Sebastian im Traum; Feuervogel-Suite (Fassung: 1919)",
    title: "Wiederholung",
    composers: "Dvorak; Henze; Strawinsky",
    composerGivenNames: "Antonin; Hans Werner; Igor",
    titles: "Wiederholung",
    duration: "01:08:00",
    soloistsLastNames: "Faust",
    soloistsGivenNames: "Isabelle",
    instruments: "Solist /-in Violine\"   \"",
    conductorLastName: "Popelka",
    conductorGivenNames: "Petr",
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-07-08 00:00:00",
    start: "10:00:00",
    type: "Kinderkonzert",
    venue: "Isarphilharmonie",
    city: "M\u00fcnchen",
    series: null,
    programm: "Ma m\u00e8re l'Oye",
    title: null,
    composers: "Ravel",
    composerGivenNames: "Maurice",
    titles: null,
    duration: "00:29:00",
    soloistsLastNames: null,
    soloistsGivenNames: null,
    instruments: null,
    conductorLastName: "N.N.",
    conductorGivenNames: null,
    capacity: 1800,
    link: DEFAULT_CONCERT_LINK
  },
  {
    date: "2026-07-12 00:00:00",
    start: "20:00:00",
    type: "Konzert Open Air",
    venue: "Odeonsplatz, Feldherrnhalle",
    city: "M\u00fcnchen",
    series: null,
    programm: "Violinkonzert Nr. 1",
    title: "Klassik am Odeonsplatz",
    composers: "Bruch",
    composerGivenNames: "Max",
    titles: "Klassik am Odeonsplatz",
    duration: "00:25:00",
    soloistsLastNames: "Jansen",
    soloistsGivenNames: "Janine",
    instruments: "Solist /-in Violine\"   \"",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 0,
    link: DEFAULT_CONCERT_LINK
  }
];

export { concerts as CONCERTS };
