export const DEFAULT_CONCERT_LINK = "https://www.mphil.de/konzerte-und-karten/kalender-2024-2025#j44933";

const concerts = [
  {
    date: "06.06.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "H4",
    programm: "Atmosphères; Sinfonie Nr.2; Konzert für Violine und Orchester D-Dur",
    title: "",
    composers: "Ligeti; Brahms; Strawinsky",
    composerGivenNames: "György; Johannes; Igor",
    titles: "",
    duration: "01:12:00",
    soloistsLastNames: "Kavakos",
    soloistsGivenNames: "Leonidas",
    instruments: "Violine",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 0,
    REnergy: 0,
    link: ""
  },
  {
    date: "06.06.2025",
    start: "21:00:00",
    type: "MPhil Late",
    venue: "Halle E",
    city: "München",
    series: "",
    programm: "",
    title: "",
    composers: "",
    composerGivenNames: "",
    titles: "",
    duration: "00:00:00",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 0,
    TExp: 0,
    REnergy: 0,
    link: ""
  },
  {
    date: "07.06.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "Atmosphères; Sinfonie Nr.2; Konzert für Violine und Orchester D-Dur",
    title: "",
    composers: "Ligeti; Brahms; Strawinsky",
    composerGivenNames: "György; Johannes; Igor",
    titles: "",
    duration: "01:12:00",
    soloistsLastNames: "Kavakos",
    soloistsGivenNames: "Leonidas",
    instruments: "Violine",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 0,
    REnergy: 0,
    link: ""
  },
  {
    date: "13.06.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "Prélude à l'après-midi d'un faune; Wesendonck Lieder (5 Titel); Symphonie Fantastique",
    title: "",
    composers: "Debussy; Wagner; Berlioz",
    composerGivenNames: "Claude; Richard; Hector",
    titles: "",
    duration: "01:25:00",
    soloistsLastNames: "Willis-Sørensen",
    soloistsGivenNames: "Rachel",
    instruments: "Solistin Stimmlage Sopran\" \"",
    conductorLastName: "Nelsons",
    conductorGivenNames: "Andris",
    capacity: 1800,
    TExp: 0,
    REnergy: 0,
    link: ""
  },
  {
    date: "14.06.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "F; I",
    programm: "Wesendonck Lieder (5 Titel); Symphonie Fantastique; Prélude à l'après-midi d'un faune",
    title: "",
    composers: "Wagner; Berlioz; Debussy",
    composerGivenNames: "Richard; Hector; Claude",
    titles: "",
    duration: "02:50:00",
    soloistsLastNames: "Willis-Sørensen",
    soloistsGivenNames: "Rachel",
    instruments: "Solistin Stimmlage Sopran\" \"",
    conductorLastName: "Nelsons",
    conductorGivenNames: "Andris",
    capacity: 1800,
    TExp: 0,
    REnergy: 0,
    link: ""
  },
  {
    date: "22.06.2025",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Streichtrio; Streichquartett F-Dur op. 35; Streichquartett g-Moll, op. 10",
    title: "Dreimalig einmalig – 8. Kammerkonzert",
    composers: "Francaix; Ravel; Debussy",
    composerGivenNames: "Jean; Maurice; Claude",
    titles: "Dreimalig einmalig – 8. Kammerkonzert",
    duration: "04:28:00",
    soloistsLastNames: "Stark; Risbet; Mijnders; Vaudé",
    soloistsGivenNames: "Asami; Julie Amandine Laure; Floris; Céline Marie",
    instruments: "2. Violine; Bratsche; Violoncello; 1. Violine",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 1,
    REnergy: 1,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/419281"
  },
  {
    date: "24.06.2025",
    start: "19:30:00",
    type: "Sonderkammerkonzert",
    venue: "Rathaussaal",
    city: "München",
    series: "",
    programm: "Ouvertüre zu The Boatswain's Mate\" \"; Suite aus Les Boréades\" \"; Voodoo Dolls; Improvisation über Tonmaterial aus explosante fixe von Pierre Boulez; Sinfonia in F-Dur; Strum; Streichquintett Es-Dur; Ouverture zu Céphale et Procris\" \"; Sinfonie Nr. 3 g-moll op. 36; Leyendas: An Andean Walkabout; Intermezzo funèbre",
    title: "Regenbogen-Konzert",
    composers: "Smyth; Rameau; Montgomery; Strauch; Ahlefeldt; Farrenc; Jaquet de La Guerre; Frank",
    composerGivenNames: "Dame Ethel Mary; Jean-Philippe; Jessie; Alexander; Maria Theresia von; Louise; Élisabeth-Claude; Gabriela Lena",
    titles: "Regenbogen-Konzert",
    duration: "06:45:00",
    soloistsLastNames: "Weiskopf; Tolpygo; Zaunschirm; Rieke; Arnholdt",
    soloistsGivenNames: "Alexander Franz; Vladimir; Johanna; Jannis Michael; Friederike Luise",
    instruments: "Kontrabaß; 1. Violine; 2. Violine; Bratsche; Violoncello",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 0,
    TExp: 4,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/430638"
  },
  {
    date: "26.06.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "The planets; Klavierkonzert Nr. 3",
    title: "Rachmaninow / Holst",
    composers: "Holst; Rachmaninoff",
    composerGivenNames: "Gustav; Sergei",
    titles: "Rachmaninow / Holst",
    duration: "01:32:00",
    soloistsLastNames: "Philharmonischer Chor München; Sorita",
    soloistsGivenNames: "Kyohei",
    instruments: "Chor; Solopianist/ in",
    conductorLastName: "Gimeno",
    conductorGivenNames: "Gustavo",
    capacity: 1800,
    TExp: 1,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/417341"
  },
  {
    date: "27.06.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "Jugendkonzert",
    programm: "The planets; Klavierkonzert Nr. 3",
    title: "Uni-Konzert & U30 – Rachmaninow/Holst",
    composers: "Holst; Rachmaninoff",
    composerGivenNames: "Gustav; Sergei",
    titles: "Uni-Konzert & U30 – Rachmaninow/Holst",
    duration: "01:32:00",
    soloistsLastNames: "Philharmonischer Chor München; Sorita",
    soloistsGivenNames: "Kyohei",
    instruments: "Chor; Solopianist/ in",
    conductorLastName: "Gimeno",
    conductorGivenNames: "Gustavo",
    capacity: 1800,
    TExp: 1,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/425617"
  },
  {
    date: "29.06.2025",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "The planets; Klavierkonzert Nr. 3",
    title: "Rachmaninow / Holst",
    composers: "Holst; Rachmaninoff",
    composerGivenNames: "Gustav; Sergei",
    titles: "Rachmaninow / Holst",
    duration: "01:32:00",
    soloistsLastNames: "Philharmonischer Chor München; Sorita",
    soloistsGivenNames: "Kyohei",
    instruments: "Chor; Solopianist/ in",
    conductorLastName: "Gimeno",
    conductorGivenNames: "Gustavo",
    capacity: 1800,
    TExp: 1,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/417342"
  },
  {
    date: "29.06.2025",
    start: "17:00:00",
    type: "Konzert",
    venue: "",
    city: "",
    series: "",
    programm: "",
    title: "Symphonic Mob",
    composers: "",
    composerGivenNames: "",
    titles: "Symphonic Mob",
    duration: "",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 0,
    TExp: 5,
    REnergy: 4,
    link: "https://www.symphonic-mob.de/stadt/muenchen/anmelden"
  },
  {
    date: "02.07.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "Violinkonzert; Sinfonie Nr.9 (Aus der Neuen Welt\") \"",
    title: "Brahms / Dvořák",
    composers: "Brahms; Dvorak",
    composerGivenNames: "Johannes; Antonin",
    titles: "Brahms / Dvořák",
    duration: "01:16:00",
    soloistsLastNames: "Hahn",
    soloistsGivenNames: "Hilary",
    instruments: "Violine",
    conductorLastName: "Orozco-Estrada",
    conductorGivenNames: "Andrés",
    capacity: 1800,
    TExp: 1,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/417343"
  },
  {
    date: "02.07.2025",
    start: "22:00:00",
    type: "Konzert",
    venue: "",
    city: "",
    series: "",
    programm: "",
    title: "»MPHIL Late«",
    composers: "",
    composerGivenNames: "",
    titles: "»MPHIL Late«",
    duration: "",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 0,
    TExp: 6,
    REnergy: 6,
    link: "eintritt frei"
  },
  {
    date: "03.07.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "F; G4",
    programm: "Violinkonzert; Sinfonie Nr.9 (Aus der Neuen Welt\") \"",
    title: "Brahms / Dvořák",
    composers: "Brahms; Dvorak",
    composerGivenNames: "Johannes; Antonin",
    titles: "Brahms / Dvořák",
    duration: "02:32:00",
    soloistsLastNames: "Hahn",
    soloistsGivenNames: "Hilary",
    instruments: "Violine",
    conductorLastName: "Orozco-Estrada",
    conductorGivenNames: "Andrés",
    capacity: 1800,
    TExp: 1,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/417344"
  },
  {
    date: "03.07.2025",
    start: "22:00:00",
    type: "Konzert",
    venue: "",
    city: "",
    series: "",
    programm: "",
    title: "»MPHIL Late«",
    composers: "",
    composerGivenNames: "",
    titles: "»MPHIL Late«",
    duration: "",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 0,
    TExp: 6,
    REnergy: 6,
    link: "eintritt frei"
  },
  {
    date: "13.07.2025",
    start: "20:00:00",
    type: "Konzert Open Air",
    venue: "Odeonsplatz, Feldherrnhalle",
    city: "München",
    series: "",
    programm: "Violinkonzert D-Dur; Sinfonische Tänze",
    title: "Klassik am Odeonsplatz",
    composers: "Beethoven; Rachmaninoff",
    composerGivenNames: "Ludwig van; Sergei",
    titles: "Klassik am Odeonsplatz",
    duration: "01:19:00",
    soloistsLastNames: "Batiashvili",
    soloistsGivenNames: "Elisabeth",
    instruments: "Solist /-in Violine\" \"",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 0,
    TExp: 1,
    REnergy: 4,
    link: "https://www.muenchenticket.de/event/klassik-am-odeonsplatz-2025-muenchner-philharmoniker-30871/426293/"
  },
  {
    date: "16.07.2025",
    start: "10:00:00",
    type: "Kinderkonzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "",
    programm: "Konferenz der Tiere; Kammersinfonie für Streichorchester; Suite Mignonne; Valse Triste; Arlequin",
    title: "Die Konferenz der Tiere – Kinderkonzert",
    composers: "diverse Komponisten; Schostakowitsch; Sibelius; Hoffmann",
    composerGivenNames: "Dmitrij; Jean; E.T.A.",
    titles: "Die Konferenz der Tiere – Kinderkonzert",
    duration: "01:58:52",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "Yoon",
    conductorGivenNames: "Hankyeol",
    capacity: 1800,
    TExp: 3,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/422183"
  },
  {
    date: "09.09.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "E4",
    programm: "Sinfonie Nr.8 (Unvollendete\") \"; Konzert für Violoncello; Tristan: Vorspiel und Isoldes Liebestod",
    title: "Elger Schubert Wagner",
    composers: "Schubert; Elgar; Wagner",
    composerGivenNames: "Franz; Edward; Richard",
    titles: "Elger Schubert Wagner",
    duration: "01:10:00",
    soloistsLastNames: "Gabetta",
    soloistsGivenNames: "Sol",
    instruments: "Violoncello",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 2,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432277"
  },
  {
    date: "10.09.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "Konzert für Violoncello; Tristan: Vorspiel und Isoldes Liebestod; Sinfonie Nr.8 (Unvollendete\") \"",
    title: "Elger Schubert Wagner",
    composers: "Elgar; Wagner; Schubert",
    composerGivenNames: "Edward; Richard; Franz",
    titles: "Elger Schubert Wagner",
    duration: "01:10:00",
    soloistsLastNames: "Gabetta",
    soloistsGivenNames: "Sol",
    instruments: "Violoncello",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 2,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432178"
  },
  {
    date: "27.09.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "F; I",
    programm: "Sinfonie Nr.8; Klavierkonzert Nr. 3; Peer Gynt-Suite Nr.1",
    title: "Grieg Prokofjew Dvorak",
    composers: "Dvorak; Prokofieff; Grieg",
    composerGivenNames: "Antonin; Sergej; Edvard",
    titles: "Grieg Prokofjew Dvorak",
    duration: "02:36:00",
    soloistsLastNames: "Montero",
    soloistsGivenNames: "Gabriela",
    instruments: "Solopianist/ in",
    conductorLastName: "Stasevska",
    conductorGivenNames: "Dalia",
    capacity: 1800,
    TExp: 2,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432256"
  },
  {
    date: "28.09.2025",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "Sinfonie Nr.8; Klavierkonzert Nr. 3; Peer Gynt-Suite Nr.1",
    title: "Grieg Prokofjew Dvorak",
    composers: "Dvorak; Prokofieff; Grieg",
    composerGivenNames: "Antonin; Sergej; Edvard",
    titles: "Grieg Prokofjew Dvorak",
    duration: "01:18:00",
    soloistsLastNames: "Montero",
    soloistsGivenNames: "Gabriela",
    instruments: "Solopianist/ in",
    conductorLastName: "Stasevska",
    conductorGivenNames: "Dalia",
    capacity: 1800,
    TExp: 2,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432269"
  },
  {
    date: "08.10.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "Le Corsaire; Les nuits d'été - Sommernächte; La mer; Caída libre",
    title: "Brunea-Boulmier Berlioz Debussy",
    composers: "Berlioz; Debussy; Bruneau-Boulmier",
    composerGivenNames: "Hector; Claude; Rodolphe",
    titles: "Brunea-Boulmier Berlioz Debussy",
    duration: "01:12:00",
    soloistsLastNames: "Crebassa",
    soloistsGivenNames: "Marianne",
    instruments: "Solistin Stimmlage Mezzosopran\" \"",
    conductorLastName: "Nagano",
    conductorGivenNames: "Kent",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432179"
  },
  {
    date: "09.10.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "Le Corsaire; Les nuits d'été - Sommernächte; La mer; Caída libre",
    title: "Brunea-Boulmier Berlioz Debussy",
    composers: "Berlioz; Debussy; Bruneau-Boulmier",
    composerGivenNames: "Hector; Claude; Rodolphe",
    titles: "Brunea-Boulmier Berlioz Debussy",
    duration: "01:12:00",
    soloistsLastNames: "Crebassa",
    soloistsGivenNames: "Marianne",
    instruments: "Solistin Stimmlage Mezzosopran\" \"",
    conductorLastName: "Nagano",
    conductorGivenNames: "Kent",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432187"
  },
  {
    date: "12.10.2025",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Phantasy Quartet on British Folkssongs, op. 36; Streichquartett e-Moll; 5 Fantasias in 4 Parts; Phantasy Quartet",
    title: "1. Kammerkonzert »Phantasy«",
    composers: "Holst; Smyth; Purcell",
    composerGivenNames: "Gustav; Dame Ethel Mary; Henry; Imogen",
    titles: "1. Kammerkonzert »Phantasy«",
    duration: "00:00:00",
    soloistsLastNames: "Hausdorf; Fordham; Shevlin; Eichler",
    soloistsGivenNames: "David; Simon Michael; Julian Peter; Valentin",
    instruments: "Violoncello; 2. Violine; 1. Violine; Bratsche",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 3,
    REnergy: 1,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432335"
  },
  {
    date: "18.10.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "Fanfare Ritmico; Konzert für Klavier F-Dur; Sinfonie Nr.3",
    title: "Klangwelten der Gegenwart",
    composers: "Higdon; Gershwin; Copland",
    composerGivenNames: "Jennifer; George; Aaron",
    titles: "Klangwelten der Gegenwart",
    duration: "01:18:00",
    soloistsLastNames: "Buchbinder",
    soloistsGivenNames: "Rudolf",
    instruments: "Solopianist/ in",
    conductorLastName: "Macelaru",
    conductorGivenNames: "Cristian",
    capacity: 1800,
    TExp: 4,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432209"
  },
  {
    date: "19.10.2025",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "Sinfonie Nr.3; Fanfare Ritmico; Konzert für Klavier F-Dur",
    title: "Klangwelten der Gegenwart",
    composers: "Copland; Higdon; Gershwin",
    composerGivenNames: "Aaron; Jennifer; George",
    titles: "Klangwelten der Gegenwart",
    duration: "01:18:00",
    soloistsLastNames: "Buchbinder",
    soloistsGivenNames: "Rudolf",
    instruments: "Solopianist/ in",
    conductorLastName: "Macelaru",
    conductorGivenNames: "Cristian",
    capacity: 1800,
    TExp: 4,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432270"
  },
  {
    date: "24.10.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "Sinfonia; Images - 1.Gigues; Images - 2.Ibéria; Images - 3.Rondes des printemps",
    title: "100. Geburtstage (Berio)",
    composers: "Berio; Debussy",
    composerGivenNames: "Luciano; Claude",
    titles: "100. Geburtstage (Berio)",
    duration: "01:46:00",
    soloistsLastNames: "Bürgi; Cantando Admont",
    soloistsGivenNames: "Cordula",
    instruments: "Leiter eines fremden Chores; Ensemble /Solistengruppe",
    conductorLastName: "Pintscher",
    conductorGivenNames: "Matthias",
    capacity: 1800,
    TExp: 4,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432201"
  },
  {
    date: "25.10.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "G4; F",
    programm: "Images - 3.Rondes des printemps; Sinfonia; Images - 1.Gigues; Images - 2.Ibéria",
    title: "100. Geburtstage (Berio)",
    composers: "Debussy; Berio",
    composerGivenNames: "Claude; Luciano",
    titles: "100. Geburtstage (Berio)",
    duration: "03:32:00",
    soloistsLastNames: "Bürgi; Cantando Admont",
    soloistsGivenNames: "Cordula",
    instruments: "Leiter eines fremden Chores; Ensemble /Solistengruppe",
    conductorLastName: "Pintscher",
    conductorGivenNames: "Matthias",
    capacity: 1800,
    TExp: 4,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432257"
  },
  {
    date: "29.10.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "Missa pro defunctis; Sound and Fury; Rendering für Orchester",
    title: "Meister der Innovation",
    composers: "Haydn; Clyne; Schubert",
    composerGivenNames: "Michael; Anna; Franz",
    titles: "Meister der Innovation",
    duration: "04:35:00",
    soloistsLastNames: "Philharmonischer Chor München; Tilling; Foster-Williams; Puskarz Thomas; Maqungo",
    soloistsGivenNames: "Camilla; Andrew; Xenia; Siyabonga",
    instruments: "Chor; Solistin Stimmlage Sopran\" \"; Solist Stimmlage Bass\" \"; Solistin Stimmlage Mezzosopran\" \"; Solist Stimmlage Tenor\" \"",
    conductorLastName: "Minasi",
    conductorGivenNames: "Ricardo",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432180"
  },
  {
    date: "30.10.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "Missa pro defunctis; Sound and Fury; Rendering für Orchester",
    title: "Meister der Innovation",
    composers: "Haydn; Clyne; Schubert",
    composerGivenNames: "Michael; Anna; Franz",
    titles: "Meister der Innovation",
    duration: "04:35:00",
    soloistsLastNames: "Philharmonischer Chor München; Tilling; Foster-Williams; Puskarz Thomas; Maqungo",
    soloistsGivenNames: "Camilla; Andrew; Xenia; Siyabonga",
    instruments: "Chor; Solistin Stimmlage Sopran\" \"; Solist Stimmlage Bass\" \"; Solistin Stimmlage Mezzosopran\" \"; Solist Stimmlage Tenor\" \"",
    conductorLastName: "Minasi",
    conductorGivenNames: "Ricardo",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432189"
  },
  {
    date: "02.11.2025",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Don Giovanni - eine Oper im Taschenformat",
    title: "2. Kammerkonzert »Don Giovanni«",
    composers: "Mozart",
    composerGivenNames: "Wolfgang Amadeus",
    titles: "2. Kammerkonzert »Don Giovanni«",
    duration: "00:00:00",
    soloistsLastNames: "Kofler; Courtin; Sigl; Müller; Kasparek",
    soloistsGivenNames: "Michael Martin; Clément Pierre Marie; Burkhard Johannes Friedrich; Elisabeth Veronika; Gottfried Franz",
    instruments: "Flöte; 2. Violine; Bratsche; Violoncello; Sprecher/-in",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 2,
    REnergy: 1,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432337"
  },
  {
    date: "14.11.2025",
    start: "18:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "Jugendkonzert",
    programm: "Klavierkonzert Nr. 2; Sinfonie Nr.2 h-moll; Moscow Cheryomushki: Suite (1.-3. Satz)",
    title: "1. Jugendkonzert",
    composers: "Rachmaninoff; Borodin; Schostakowitsch",
    composerGivenNames: "Sergei; Alexander; Dmitrij",
    titles: "1. Jugendkonzert",
    duration: "01:16:00",
    soloistsLastNames: "Gerstein",
    soloistsGivenNames: "Kirill",
    instruments: "Solopianist/ in",
    conductorLastName: "Rouvali",
    conductorGivenNames: "Santtu-Matias",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: ""
  },
  {
    date: "15.11.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "K4",
    programm: "Moscow Cheryomushki: Suite (1.-3. Satz); Klavierkonzert Nr. 2; Sinfonie Nr.2 h-moll",
    title: "Rachmaninow / Bartholdy / Tschaikowsky",
    composers: "Schostakowitsch; Rachmaninoff; Borodin",
    composerGivenNames: "Dmitrij; Sergei; Alexander",
    titles: "Rachmaninow / Bartholdy / Tschaikowsky",
    duration: "01:16:00",
    soloistsLastNames: "Gerstein",
    soloistsGivenNames: "Kirill",
    instruments: "Solopianist/ in",
    conductorLastName: "Rouvali",
    conductorGivenNames: "Santtu-Matias",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432331"
  },
  {
    date: "16.11.2025",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "Klavierkonzert Nr. 2; Sinfonie Nr.2 h-moll; Moscow Cheryomushki: Suite (1.-3. Satz)",
    title: "Rachmaninow / Bartholdy / Tschaikowsky",
    composers: "Rachmaninoff; Borodin; Schostakowitsch",
    composerGivenNames: "Sergei; Alexander; Dmitrij",
    titles: "Rachmaninow / Bartholdy / Tschaikowsky",
    duration: "01:16:00",
    soloistsLastNames: "Gerstein",
    soloistsGivenNames: "Kirill",
    instruments: "Solopianist/ in",
    conductorLastName: "Rouvali",
    conductorGivenNames: "Santtu-Matias",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432271"
  },
  {
    date: "20.11.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "Konzert für 2 Klaviere; Sinfonie Nr.4; Die Hebriden (oder Die Fingalshöhle\") \"",
    title: "Mendelssohn & Tschaikowsky",
    composers: "Mendelssohn-Bartholdy; Tschaikowsky",
    composerGivenNames: "Felix; Piotr Ilyich",
    titles: "Mendelssohn & Tschaikowsky",
    duration: "01:52:00",
    soloistsLastNames: "Jussen",
    soloistsGivenNames: "Arthur; Lucas",
    instruments: "Solopianist/ in",
    conductorLastName: "Sokhiev",
    conductorGivenNames: "Tugan",
    capacity: 1800,
    TExp: 2,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432190"
  },
  {
    date: "21.11.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "Jugendkonzert",
    programm: "Konzert für 2 Klaviere; Sinfonie Nr.4; Die Hebriden (oder Die Fingalshöhle\") \"",
    title: "Uni/U30-Spezial",
    composers: "Mendelssohn-Bartholdy; Tschaikowsky",
    composerGivenNames: "Felix; Piotr Ilyich",
    titles: "Uni/U30-Spezial",
    duration: "01:52:00",
    soloistsLastNames: "Jussen",
    soloistsGivenNames: "Arthur; Lucas",
    instruments: "Solopianist/ in",
    conductorLastName: "Sokhiev",
    conductorGivenNames: "Tugan",
    capacity: 1800,
    TExp: 2,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/436488"
  },
  {
    date: "22.11.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "Konzert für 2 Klaviere; Sinfonie Nr.4; Die Hebriden (oder Die Fingalshöhle\") \"",
    title: "Mendelssohn & Tschaikowsky",
    composers: "Mendelssohn-Bartholdy; Tschaikowsky",
    composerGivenNames: "Felix; Piotr Ilyich",
    titles: "Mendelssohn & Tschaikowsky",
    duration: "01:52:00",
    soloistsLastNames: "Jussen",
    soloistsGivenNames: "Arthur; Lucas",
    instruments: "Solopianist/ in",
    conductorLastName: "Sokhiev",
    conductorGivenNames: "Tugan",
    capacity: 1800,
    TExp: 2,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432210"
  },
  {
    date: "05.12.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "Sinfonie Nr.4 B-Dur; Arpeggione; Wilhelm Tell: Ouvertüre",
    title: "Rossini / Schubert / Beethoven",
    composers: "Beethoven; Schubert; Rossini",
    composerGivenNames: "Ludwig van; Franz; Gioacchino",
    titles: "Rossini / Schubert / Beethoven",
    duration: "01:14:00",
    soloistsLastNames: "Kobekina",
    soloistsGivenNames: "Anastasia",
    instruments: "Violoncello",
    conductorLastName: "Chang",
    conductorGivenNames: "Han-Na",
    capacity: 1800,
    TExp: 2,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432202"
  },
  {
    date: "06.12.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "E4",
    programm: "Sinfonie Nr.4 B-Dur; Arpeggione; Wilhelm Tell: Ouvertüre",
    title: "Rossini / Schubert / Beethoven",
    composers: "Beethoven; Schubert; Rossini",
    composerGivenNames: "Ludwig van; Franz; Gioacchino",
    titles: "Rossini / Schubert / Beethoven",
    duration: "01:14:00",
    soloistsLastNames: "Kobekina",
    soloistsGivenNames: "Anastasia",
    instruments: "Violoncello",
    conductorLastName: "Chang",
    conductorGivenNames: "Han-Na",
    capacity: 1800,
    TExp: 2,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432323"
  },
  {
    date: "10.12.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "El sombrero de tres picos - Suite Nr. 1; El sombrero de tres picos - Suite Nr. 2; Altar de Cuerda (Violinkonzert); Bolero; Danzón Nr. 8",
    title: "Marquez / Fritz / Falla / Ravel",
    composers: "Falla; Ortiz; Ravel; Marquez",
    composerGivenNames: "Manuel de; Gabriela; Maurice; Arturo",
    titles: "Marquez / Fritz / Falla / Ravel",
    duration: "01:14:00",
    soloistsLastNames: "Dueñas",
    soloistsGivenNames: "Maria",
    instruments: "Violine",
    conductorLastName: "Bortolameolli",
    conductorGivenNames: "Paolo",
    capacity: 1800,
    TExp: 5,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432181"
  },
  {
    date: "11.12.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "Altar de Cuerda (Violinkonzert); Bolero; Danzón Nr. 8; El sombrero de tres picos - Suite Nr. 1; El sombrero de tres picos - Suite Nr. 2",
    title: "Marquez / Fritz / Falla / Ravel",
    composers: "Ortiz; Ravel; Marquez; Falla",
    composerGivenNames: "Gabriela; Maurice; Arturo; Manuel de",
    titles: "Marquez / Fritz / Falla / Ravel",
    duration: "01:14:00",
    soloistsLastNames: "Dueñas",
    soloistsGivenNames: "Maria",
    instruments: "Violine",
    conductorLastName: "Bortolameolli",
    conductorGivenNames: "Paolo",
    capacity: 1800,
    TExp: 5,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432191"
  },
  {
    date: "12.12.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "F; G4",
    programm: "Altar de Cuerda (Violinkonzert); Bolero; Danzón Nr. 8; El sombrero de tres picos - Suite Nr. 1; El sombrero de tres picos - Suite Nr. 2",
    title: "Marquez / Fritz / Falla / Ravel",
    composers: "Ortiz; Ravel; Marquez; Falla",
    composerGivenNames: "Gabriela; Maurice; Arturo; Manuel de",
    titles: "Marquez / Fritz / Falla / Ravel",
    duration: "02:28:00",
    soloistsLastNames: "Dueñas",
    soloistsGivenNames: "Maria",
    instruments: "Violine",
    conductorLastName: "Bortolameolli",
    conductorGivenNames: "Paolo",
    capacity: 1800,
    TExp: 5,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432259"
  },
  {
    date: "14.12.2025",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Nocturne and Scherzo; Streichtrio op. 19; Phantasy Quintet; Streichtrio D-Dur op. 6",
    title: "3. Kammerkonzert »Very British«",
    composers: "Vaughan Williams; Berkeley; Smyth",
    composerGivenNames: "Ralph; Lennox; Dame Ethel Mary",
    titles: "3. Kammerkonzert »Very British«",
    duration: "00:00:00",
    soloistsLastNames: "Tolpygo; Rieke; Risbet; Wohlgemuth; Shevlin",
    soloistsGivenNames: "Vladimir; Jannis Michael; Julie Amandine Laure; Joachim Eckart; Julian Peter",
    instruments: "1. Violine; Bratsche; Violoncello",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 3,
    REnergy: 1,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432342"
  },
  {
    date: "19.12.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "K4",
    programm: "Evening Hymn; Konzert in D-Dur für Trompete und Orchester; Sonata pian e forte; Psalmensymphonie; Sinfonie Nr.92 (Oxford\") \"",
    title: "Gabrieli / Gardiner / Strawinsky / Tartini / Haydn",
    composers: "Gardiner; Tartini; Gabrieli; Strawinsky; Haydn",
    composerGivenNames: "Henry Balfour; Giuseppe; Giovanni; Igor; Joseph",
    titles: "Gabrieli / Gardiner / Strawinsky / Tartini / Haydn",
    duration: "01:05:00",
    soloistsLastNames: "Philharmonischer Chor München; Segers",
    soloistsGivenNames: "Guido Lambertus",
    instruments: "Chor; Trompete",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 3,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432332"
  },
  {
    date: "20.12.2025",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "Psalmensymphonie; Sinfonie Nr.92 (Oxford\") \"; Evening Hymn; Konzert in D-Dur für Trompete und Orchester; Sonata pian e forte",
    title: "Gabrieli / Gardiner / Strawinsky / Tartini / Haydn",
    composers: "Strawinsky; Haydn; Gardiner; Tartini; Gabrieli",
    composerGivenNames: "Igor; Joseph; Henry Balfour; Giuseppe; Giovanni",
    titles: "Gabrieli / Gardiner / Strawinsky / Tartini / Haydn",
    duration: "01:05:00",
    soloistsLastNames: "Philharmonischer Chor München; Segers",
    soloistsGivenNames: "Guido Lambertus",
    instruments: "Chor; Trompete",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 3,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432211"
  },
  {
    date: "21.12.2025",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "Psalmensymphonie; Sinfonie Nr.92 (Oxford\") \"; Evening Hymn; Konzert in D-Dur für Trompete und Orchester; Sonata pian e forte",
    title: "Gabrieli / Gardiner / Strawinsky / Tartini / Haydn",
    composers: "Strawinsky; Haydn; Gardiner; Tartini; Gabrieli",
    composerGivenNames: "Igor; Joseph; Henry Balfour; Giuseppe; Giovanni",
    titles: "Gabrieli / Gardiner / Strawinsky / Tartini / Haydn",
    duration: "01:05:00",
    soloistsLastNames: "Philharmonischer Chor München; Segers",
    soloistsGivenNames: "Guido Lambertus",
    instruments: "Chor; Trompete",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 3,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432272"
  },
  {
    date: "30.12.2025",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "H4",
    programm: "Sinfonie Nr.9 d-moll",
    title: "Beethoven 9 (Silvester)",
    composers: "Beethoven",
    composerGivenNames: "Ludwig van",
    titles: "Beethoven 9 (Silvester)",
    duration: "05:25:00",
    soloistsLastNames: "Romero; Kristinnson; Kissjudit; Takala; Philharmonischer Chor München",
    soloistsGivenNames: "Angel; Johann; Anna; Tuuli",
    instruments: "Solist Stimmlage Tenor\" \"; Solist Stimmlage Bassbariton\" \"; Solistin Stimmlage Mezzosopran\" \"; Solistin Stimmlage Sopran\" \"; Chor",
    conductorLastName: "Ollikainen",
    conductorGivenNames: "Eva",
    capacity: 1800,
    TExp: 2,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432326"
  },
  {
    date: "31.12.2025",
    start: "17:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "",
    programm: "Sinfonie Nr.9 d-moll",
    title: "Beethoven 9 (Silvester)",
    composers: "Beethoven",
    composerGivenNames: "Ludwig van",
    titles: "Beethoven 9 (Silvester)",
    duration: "05:25:00",
    soloistsLastNames: "Romero; Kristinnson; Kissjudit; Takala; Philharmonischer Chor München",
    soloistsGivenNames: "Angel; Johann; Anna; Tuuli",
    instruments: "Solist Stimmlage Tenor\" \"; Solist Stimmlage Bassbariton\" \"; Solistin Stimmlage Mezzosopran\" \"; Solistin Stimmlage Sopran\" \"; Chor",
    conductorLastName: "Ollikainen",
    conductorGivenNames: "Eva",
    capacity: 1800,
    TExp: 2,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/434700"
  },
  {
    date: "09.01.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "Exsultate jubilate; Sinfonie Nr.39 Es-Dur; Sinfonie Nr.34; Die Hochzeit des Figaro - Ouvertüre; Cosi fan tutte - Ei parte..senti..ah no!\" \"; Il re pastore : L'amerò, sarò costante\" \"; La clemenza di tito: Parto, ma tu, ben mio\" \"",
    title: "Mozart-Gala",
    composers: "Mozart",
    composerGivenNames: "Wolfgang Amadeus",
    titles: "Mozart-Gala",
    duration: "01:26:00",
    soloistsLastNames: "Lezhneva",
    soloistsGivenNames: "Julia",
    instruments: "Solistin Stimmlage Sopran\" \"",
    conductorLastName: "Marcon",
    conductorGivenNames: "Andrea",
    capacity: 1800,
    TExp: 1,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432203"
  },
  {
    date: "10.01.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "Die Hochzeit des Figaro - Ouvertüre; Cosi fan tutte - Ei parte..senti..ah no!\" \"; Il re pastore : L'amerò, sarò costante\" \"; La clemenza di tito: Parto, ma tu, ben mio\" \"; Exsultate jubilate; Sinfonie Nr.39 Es-Dur; Sinfonie Nr.34",
    title: "Mozart-Gala",
    composers: "Mozart",
    composerGivenNames: "Wolfgang Amadeus",
    titles: "Mozart-Gala",
    duration: "01:26:00",
    soloistsLastNames: "Lezhneva",
    soloistsGivenNames: "Julia",
    instruments: "Solistin Stimmlage Sopran\" \"",
    conductorLastName: "Marcon",
    conductorGivenNames: "Andrea",
    capacity: 1800,
    TExp: 1,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432212"
  },
  {
    date: "16.01.2026",
    start: "10:00:00",
    type: "Kinderkonzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "",
    programm: "Der Schneemann; Schauspiel-Ouvertüre",
    title: "Kinderkonzert Der Schneemann",
    composers: "Korngold",
    composerGivenNames: "Erich",
    titles: "Kinderkonzert Der Schneemann",
    duration: "03:40:00",
    soloistsLastNames: "Koerselman; Schausberger; Hackspiel; Bufe",
    soloistsGivenNames: "Annechien; Angela; Florian; Béla",
    instruments: "Regisseur; Schauspieler/in",
    conductorLastName: "Venzago",
    conductorGivenNames: "Gabriel",
    capacity: 1800,
    TExp: 3,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/435168"
  },
  {
    date: "16.01.2026",
    start: "15:00:00",
    type: "Kinderkonzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "",
    programm: "Der Schneemann; Schauspiel-Ouvertüre",
    title: "Familienkonzert Der Schneemann",
    composers: "Korngold",
    composerGivenNames: "Erich",
    titles: "Familienkonzert Der Schneemann",
    duration: "03:40:00",
    soloistsLastNames: "Koerselman; Schausberger; Hackspiel; Bufe",
    soloistsGivenNames: "Annechien; Angela; Florian; Béla",
    instruments: "Regisseur; Schauspieler/in",
    conductorLastName: "Venzago",
    conductorGivenNames: "Gabriel",
    capacity: 1800,
    TExp: 3,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/435169"
  },
  {
    date: "18.01.2026",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Zodiac / Tierkreis; Streich-Quintett G-Dur op. 77; Suite Espagnole",
    title: "4. Kammerkonzert »Durch Raum und Zeit«",
    composers: "Stockhausen; Dvorak; Albeniz",
    composerGivenNames: "Karlheinz; Antonin; Isaac",
    titles: "4. Kammerkonzert »Durch Raum und Zeit«",
    duration: "00:00:00",
    soloistsLastNames: "Schwarzfischer; Risbet; Margasyuk; von der Nahmer; Schmitz; von Neumann-Cosel; Gruber; Giannotti",
    soloistsGivenNames: "Mia; Julie Amandine Laure; Victoria; Manuel; Katharina; Ulrich Vitus; Alexandra Maria; Raffaele",
    instruments: "Horn; Bratsche; 1. Violine; Violoncello; 2. Violine; Kontrabaß; Klarinette; Fagott",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432338"
  },
  {
    date: "21.01.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "Devotion; Sinfonische Ballade für Cello und Orchester; Fancy Free; Kinah",
    title: "Korngold / Mackeben / Slatkin / Bernstein",
    composers: "Korngold; Mackeben; Bernstein; Slatkin",
    composerGivenNames: "Erich; Theo; Leonard",
    titles: "Korngold / Mackeben / Slatkin / Bernstein",
    duration: "01:10:00",
    soloistsLastNames: "Mijnders",
    soloistsGivenNames: "Floris",
    instruments: "Violoncello",
    conductorLastName: "Marshall",
    conductorGivenNames: "Wayne",
    capacity: 1800,
    TExp: 5,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432182"
  },
  {
    date: "22.01.2026",
    start: "18:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "Jugendkonzert",
    programm: "Sinfonische Ballade für Cello und Orchester; Fancy Free; Devotion",
    title: "2. Jugendkonzert Hollywood & Broadway",
    composers: "Mackeben; Bernstein; Korngold",
    composerGivenNames: "Theo; Leonard; Erich",
    titles: "2. Jugendkonzert Hollywood & Broadway",
    duration: "00:57:00",
    soloistsLastNames: "Mijnders",
    soloistsGivenNames: "Floris",
    instruments: "Violoncello",
    conductorLastName: "Marshall",
    conductorGivenNames: "Wayne",
    capacity: 1800,
    TExp: 5,
    REnergy: 4,
    link: ""
  },
  {
    date: "23.01.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "K4",
    programm: "Devotion; Sinfonische Ballade für Cello und Orchester; Fancy Free; Kinah",
    title: "Korngold / Mackeben / Slatkin / Bernstein",
    composers: "Korngold; Mackeben; Bernstein; Slatkin",
    composerGivenNames: "Erich; Theo; Leonard",
    titles: "Korngold / Mackeben / Slatkin / Bernstein",
    duration: "01:10:00",
    soloistsLastNames: "Mijnders",
    soloistsGivenNames: "Floris",
    instruments: "Violoncello",
    conductorLastName: "Marshall",
    conductorGivenNames: "Wayne",
    capacity: 1800,
    TExp: 5,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432333"
  },
  {
    date: "28.01.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "F; I",
    programm: "Pelléas und Mélisande; Klavierkonzert Nr.27; Prélude à l'après-midi d'un faune",
    title: "Debussy / Mozart / Schönberg",
    composers: "Schönberg; Mozart; Debussy",
    composerGivenNames: "Arnold; Wolfgang Amadeus; Claude",
    titles: "Debussy / Mozart / Schönberg",
    duration: "02:42:00",
    soloistsLastNames: "Shani",
    soloistsGivenNames: "Lahav",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432260"
  },
  {
    date: "29.01.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "Pelléas und Mélisande; Klavierkonzert Nr.27; Prélude à l'après-midi d'un faune",
    title: "Debussy / Mozart / Schönberg",
    composers: "Schönberg; Mozart; Debussy",
    composerGivenNames: "Arnold; Wolfgang Amadeus; Claude",
    titles: "Debussy / Mozart / Schönberg",
    duration: "01:21:00",
    soloistsLastNames: "Shani",
    soloistsGivenNames: "Lahav",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432195"
  },
  {
    date: "30.01.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "Pelléas und Mélisande; Klavierkonzert Nr.27; Prélude à l'après-midi d'un faune",
    title: "Debussy / Mozart / Schönberg",
    composers: "Schönberg; Mozart; Debussy",
    composerGivenNames: "Arnold; Wolfgang Amadeus; Claude",
    titles: "Debussy / Mozart / Schönberg",
    duration: "01:21:00",
    soloistsLastNames: "Shani",
    soloistsGivenNames: "Lahav",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432204"
  },
  {
    date: "14.02.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "Music for Ensemble and Orchestra; Violinkonzert; Harmonium für Chor und Orchester",
    title: "Reich / Knussen / Adams",
    composers: "Reich; Knussen; Adams",
    composerGivenNames: "Steve; Oliver; John",
    titles: "Reich / Knussen / Adams",
    duration: "01:09:00",
    soloistsLastNames: "Josefowicz; Philharmonischer Chor München",
    soloistsGivenNames: "Leila",
    instruments: "Solist /-in Violine\" \"; Chor",
    conductorLastName: "Lubman",
    conductorGivenNames: "Brad",
    capacity: 1800,
    TExp: 6,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432213"
  },
  {
    date: "15.02.2026",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "Music for Ensemble and Orchestra; Violinkonzert; Harmonium für Chor und Orchester",
    title: "Reich / Knussen / Adams",
    composers: "Reich; Knussen; Adams",
    composerGivenNames: "Steve; Oliver; John",
    titles: "Reich / Knussen / Adams",
    duration: "01:09:00",
    soloistsLastNames: "Josefowicz; Philharmonischer Chor München",
    soloistsGivenNames: "Leila",
    instruments: "Solist /-in Violine\" \"; Chor",
    conductorLastName: "Lubman",
    conductorGivenNames: "Brad",
    capacity: 1800,
    TExp: 6,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432273"
  },
  {
    date: "22.02.2026",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Flötenquartett KV 285; Quintett für Flöte, Harfe und Streichtrio; Deux Interludes; Elegiac Trio; Serenade",
    title: "5. Kammerkonzert »Nordwest-Wind«",
    composers: "Mozart; Cras; Ibert; Bax; Roussel",
    composerGivenNames: "Wolfgang Amadeus; Jean; Jacques; Arnold; Albert",
    titles: "5. Kammerkonzert »Nordwest-Wind«",
    duration: "00:00:00",
    soloistsLastNames: "Sigl; Arnholdt; Belic; Zimmermann; Okaya",
    soloistsGivenNames: "Burkhard Johannes Friedrich; Friederike Luise; Martin; Teresa Katharina; Megumi",
    instruments: "Bratsche; Violoncello; Flöte; Harfe; 1. Violine",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 3,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432339"
  },
  {
    date: "25.02.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "Klavierkonzert Nr.2 B-Dur; Blossoming II; Sinfonie Nr.2 D-Dur",
    title: "Hosokawa / Beethoven / Brahms",
    composers: "Brahms; Hosokawa; Beethoven",
    composerGivenNames: "Johannes; Toshio; Ludwig van",
    titles: "Hosokawa / Beethoven / Brahms",
    duration: "01:28:00",
    soloistsLastNames: "Levit",
    soloistsGivenNames: "Igor",
    instruments: "Solopianist/ in",
    conductorLastName: "Manacorda",
    conductorGivenNames: "Antonello",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432183"
  },
  {
    date: "26.02.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "Klavierkonzert Nr.2 B-Dur; Blossoming II; Sinfonie Nr.2 D-Dur",
    title: "Hosokawa / Beethoven / Brahms",
    composers: "Brahms; Hosokawa; Beethoven",
    composerGivenNames: "Johannes; Toshio; Ludwig van",
    titles: "Hosokawa / Beethoven / Brahms",
    duration: "01:28:00",
    soloistsLastNames: "Levit",
    soloistsGivenNames: "Igor",
    instruments: "Solopianist/ in",
    conductorLastName: "Manacorda",
    conductorGivenNames: "Antonello",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432196"
  },
  {
    date: "27.02.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "E4",
    programm: "Klavierkonzert Nr.2 B-Dur; Blossoming II; Sinfonie Nr.2 D-Dur",
    title: "Hosokawa / Beethoven / Brahms",
    composers: "Brahms; Hosokawa; Beethoven",
    composerGivenNames: "Johannes; Toshio; Ludwig van",
    titles: "Hosokawa / Beethoven / Brahms",
    duration: "01:28:00",
    soloistsLastNames: "Levit",
    soloistsGivenNames: "Igor",
    instruments: "Solopianist/ in",
    conductorLastName: "Manacorda",
    conductorGivenNames: "Antonello",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432324"
  },
  {
    date: "06.03.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "The dream of Gerontius",
    title: "Elgar",
    composers: "Elgar",
    composerGivenNames: "Edward",
    titles: "Elgar",
    duration: "06:40:00",
    soloistsLastNames: "Philharmonischer Chor München; Foster-Williams; Taylor; Staples",
    soloistsGivenNames: "Andrew; Beth",
    instruments: "Chor; Solist Stimmlage Bass\" \"; Solistin Stimmlage Mezzosopran\" \"; Solist Stimmlage Tenor\" \"",
    conductorLastName: "Manze",
    conductorGivenNames: "Andrew",
    capacity: 1800,
    TExp: 2,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432205"
  },
  {
    date: "07.03.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "I; F",
    programm: "The dream of Gerontius",
    title: "Elgar",
    composers: "Elgar",
    composerGivenNames: "Edward",
    titles: "Elgar",
    duration: "13:20:00",
    soloistsLastNames: "Staples; Philharmonischer Chor München; Foster-Williams; Taylor",
    soloistsGivenNames: "Andrew; Beth",
    instruments: "Solist Stimmlage Tenor\" \"; Chor; Solist Stimmlage Bass\" \"; Solistin Stimmlage Mezzosopran\" \"",
    conductorLastName: "Manze",
    conductorGivenNames: "Andrew",
    capacity: 1800,
    TExp: 2,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432261"
  },
  {
    date: "11.03.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "Sinfonie Nr.4; Klavierkonzert Nr.2 B-Dur",
    title: "Beethoven / Brahms",
    composers: "Brahms; Beethoven",
    composerGivenNames: "Johannes; Ludwig van",
    titles: "Beethoven / Brahms",
    duration: "01:10:00",
    soloistsLastNames: "Buchbinder",
    soloistsGivenNames: "Rudolf",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 1,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432184"
  },
  {
    date: "12.03.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "H4",
    programm: "Sinfonie Nr.4; Klavierkonzert Nr.2 B-Dur",
    title: "Beethoven Kb 2 · Brahms 4",
    composers: "Brahms; Beethoven",
    composerGivenNames: "Johannes; Ludwig van",
    titles: "Beethoven Kb 2 · Brahms 4",
    duration: "01:10:00",
    soloistsLastNames: "Buchbinder",
    soloistsGivenNames: "Rudolf",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 1,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432327"
  },
  {
    date: "15.03.2026",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Klavierquintett Nr. 1 a-Moll op. 30; Klavierquintett c-Moll",
    title: "6. Kammerkonzert »Tiefgründig",
    composers: "Farrenc; Vaughan Williams",
    composerGivenNames: "Louise; Ralph",
    titles: "6. Kammerkonzert »Tiefgründig",
    duration: "02:30:00",
    soloistsLastNames: "Neumann; Fordham; Springorum; Müller; Rivinius",
    soloistsGivenNames: "Michael; Simon Michael; Beate; Elisabeth Veronika; Paul Konstantin",
    instruments: "Kontrabaß; 2. Violine; Bratsche; Violoncello; Solopianist/ in",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 2,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432340"
  },
  {
    date: "22.03.2026",
    start: "11:00:00",
    type: "Familienkonzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "",
    programm: "Senta und die verfluchte Partitur",
    title: "Senta und die verfluchte Partitur - Familienkonzert",
    composers: "Janosa",
    composerGivenNames: "Felix",
    titles: "Senta und die verfluchte Partitur - Familienkonzert",
    duration: "00:00:00",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "N.N.",
    conductorGivenNames: "",
    capacity: 1800,
    TExp: 5,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/435140"
  },
  {
    date: "22.03.2026",
    start: "15:00:00",
    type: "Familienkonzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "",
    programm: "Senta und die verfluchte Partitur",
    title: "Senta und die verfluchte Partitur - Familienkonzert",
    composers: "Janosa",
    composerGivenNames: "Felix",
    titles: "Senta und die verfluchte Partitur - Familienkonzert",
    duration: "00:00:00",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "N.N.",
    conductorGivenNames: "",
    capacity: 1800,
    TExp: 5,
    REnergy: 5,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/435141"
  },
  {
    date: "28.03.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "Swaddling Silk and Gossamer Rain; Violinkonzert D-Dur; Enigma variations",
    title: "Koide / Tschaikowski / Elgar",
    composers: "Koide; Tschaikowsky; Elgar",
    composerGivenNames: "Noriko; Piotr Ilyich; Edward",
    titles: "Koide / Tschaikowski / Elgar",
    duration: "01:19:00",
    soloistsLastNames: "Hadelich",
    soloistsGivenNames: "Augustin",
    instruments: "Solist /-in Violine\" \"",
    conductorLastName: "Chan",
    conductorGivenNames: "Elim",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432214"
  },
  {
    date: "29.03.2026",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "Swaddling Silk and Gossamer Rain; Violinkonzert D-Dur; Enigma variations",
    title: "Koide / Tschaikowski / Elgar",
    composers: "Koide; Tschaikowsky; Elgar",
    composerGivenNames: "Noriko; Piotr Ilyich; Edward",
    titles: "Koide / Tschaikowski / Elgar",
    duration: "01:19:00",
    soloistsLastNames: "Hadelich",
    soloistsGivenNames: "Augustin",
    instruments: "Solist /-in Violine\" \"",
    conductorLastName: "Chan",
    conductorGivenNames: "Elim",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432274"
  },
  {
    date: "17.04.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "Sinfonie Nr.7 A-Dur; L'apothéose de la Danse\" \"",
    title: "Rameau / Beethoven",
    composers: "Beethoven; Rameau",
    composerGivenNames: "Ludwig van; Jean-Philippe",
    titles: "Rameau / Beethoven",
    duration: "01:17:00",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "Pichon",
    conductorGivenNames: "Raphael",
    capacity: 1800,
    TExp: 2,
    REnergy: 6,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432206"
  },
  {
    date: "18.04.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "L'apothéose de la Danse\" \"; Sinfonie Nr.7 A-Dur",
    title: "Rameau / Beethoven",
    composers: "Rameau; Beethoven",
    composerGivenNames: "Jean-Philippe; Ludwig van",
    titles: "Rameau / Beethoven",
    duration: "01:17:00",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "Pichon",
    conductorGivenNames: "Raphael",
    capacity: 1800,
    TExp: 2,
    REnergy: 6,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432215"
  },
  {
    date: "19.04.2026",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Variationen über Nango ti deo\" \"; Serenade für Streichtrio C-Dur KV 648; Streichquartett F-Dur KV 590; Omar; Camino pro vereda",
    title: "Entdeckungen - 7. Kammerkonzert",
    composers: "Campo; Mozart; Alyamani",
    composerGivenNames: "Jenny Peña; Wolfgang Amadeus; MAias",
    titles: "Entdeckungen - 7. Kammerkonzert",
    duration: "00:00:00",
    soloistsLastNames: "von der Nahmer; Courtin; Metz; Sellheim",
    soloistsGivenNames: "Manuel; Clément Pierre Marie; Georg Bernhard; Konstantin Alexander",
    instruments: "Violoncello; 2. Violine; Bratsche",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 4,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432341"
  },
  {
    date: "23.04.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "Sinfonie Nr.1; Klavierkonzert Nr.1 C-Dur",
    title: "Beethoven Kb 1 · Mahler 1",
    composers: "Mahler; Beethoven",
    composerGivenNames: "Gustav; Ludwig van",
    titles: "Beethoven Kb 1 · Mahler 1",
    duration: "01:26:00",
    soloistsLastNames: "Cho",
    soloistsGivenNames: "Seong-Jin",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 2,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432198"
  },
  {
    date: "24.04.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "F; G4",
    programm: "Klavierkonzert Nr.1 C-Dur; Sinfonie Nr.1",
    title: "Beethoven Kb 1 · Mahler 1",
    composers: "Beethoven; Mahler",
    composerGivenNames: "Ludwig van; Gustav",
    titles: "Beethoven Kb 1 · Mahler 1",
    duration: "02:52:00",
    soloistsLastNames: "Cho",
    soloistsGivenNames: "Seong-Jin",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 2,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432262"
  },
  {
    date: "27.04.2026",
    start: "18:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "Jugendkonzert",
    programm: "Klavierkonzert Nr. 2; Don Juan",
    title: "3. Jugendkonzert",
    composers: "Prokofieff; Strauss",
    composerGivenNames: "Sergej; Richard",
    titles: "3. Jugendkonzert",
    duration: "00:48:00",
    soloistsLastNames: "Cho",
    soloistsGivenNames: "Seong-Jin",
    instruments: "Solopianist/ in",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 1800,
    TExp: 3,
    REnergy: 6,
    link: "https://www.mphil.de/konzerte-und-karten/kalender/konzerte/strauss-prokofjew-2026-04-27-4917"
  },
  {
    date: "23.05.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "H4",
    programm: "Finlandia; Klavierkonzert Nr. 1; Sinfonie Nr.2 (London\") \"",
    title: "Sibelius / Rautavaara / Vaughan Williams",
    composers: "Sibelius; Rautavaara; Vaughan Williams",
    composerGivenNames: "Jean; Einojuhani; Ralph",
    titles: "Sibelius / Rautavaara / Vaughan Williams",
    duration: "01:06:00",
    soloistsLastNames: "Wang",
    soloistsGivenNames: "Yuja",
    instruments: "Solopianist/ in",
    conductorLastName: "Peltokowski",
    conductorGivenNames: "Tarmo",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432328"
  },
  {
    date: "24.05.2026",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "Finlandia; Klavierkonzert Nr. 1; Sinfonie Nr.2 (London\") \"",
    title: "Sibelius / Rautavaara / Vaughan Williams",
    composers: "Sibelius; Rautavaara; Vaughan Williams",
    composerGivenNames: "Jean; Einojuhani; Ralph",
    titles: "Sibelius / Rautavaara / Vaughan Williams",
    duration: "01:06:00",
    soloistsLastNames: "Wang",
    soloistsGivenNames: "Yuja",
    instruments: "Solopianist/ in",
    conductorLastName: "Peltokowski",
    conductorGivenNames: "Tarmo",
    capacity: 1800,
    TExp: 3,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432275"
  },
  {
    date: "29.05.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "Klavierkonzert; L'Arlésienne-Suite Nr.2; Khovantchina: Vorspiel zum 1. Akt; L'Arlésienne-Suite Nr.1",
    title: "Mussorgsky / Chatschaturjan / Bizet",
    composers: "Khatchaturian; Bizet; Mussorgsky",
    composerGivenNames: "Aram; Georges; Modest",
    titles: "Mussorgsky / Chatschaturjan / Bizet",
    duration: "01:14:00",
    soloistsLastNames: "Gigashvili",
    soloistsGivenNames: "Giorgi",
    instruments: "Solopianist/ in",
    conductorLastName: "Altinoglu",
    conductorGivenNames: "Alain",
    capacity: 1800,
    TExp: 5,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432207"
  },
  {
    date: "30.05.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "F; I",
    programm: "Klavierkonzert; Khovantchina: Vorspiel zum 1. Akt; L'Arlésienne-Suite Nr.1; L'Arlésienne-Suite Nr.2",
    title: "Mussorgsky / Chatschaturjan / Bizet",
    composers: "Khatchaturian; Mussorgsky; Bizet",
    composerGivenNames: "Aram; Modest; Georges",
    titles: "Mussorgsky / Chatschaturjan / Bizet",
    duration: "02:28:00",
    soloistsLastNames: "Gigashvili",
    soloistsGivenNames: "Giorgi",
    instruments: "Solopianist/ in",
    conductorLastName: "Altinoglu",
    conductorGivenNames: "Alain",
    capacity: 1800,
    TExp: 5,
    REnergy: 4,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432263"
  },
  {
    date: "13.06.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "H4",
    programm: "Feldmesse; Fürst Igor: Polovetzer Tänze; Vier letzte Lieder; Adagietto aus der Sinfonie Nr.5",
    title: "Hrůša – Mahler/ Strauss/ Martinů",
    composers: "Martinu; Borodin; Strauss; Mahler",
    composerGivenNames: "Bohuslav; Alexander; Richard; Gustav",
    titles: "Hrůša – Mahler/ Strauss/ Martinů",
    duration: "01:39:00",
    soloistsLastNames: "Philharmonischer Chor München; Brückler; Winters",
    soloistsGivenNames: "Jirí; Corinne",
    instruments: "Chor; Solist Stimmlage Bariton\" \"; Solistin Stimmlage Sopran\" \"",
    conductorLastName: "Hrusa",
    conductorGivenNames: "Jakub",
    capacity: 1800,
    TExp: 3,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432329"
  },
  {
    date: "14.06.2026",
    start: "11:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "M",
    programm: "Vier letzte Lieder; Adagietto aus der Sinfonie Nr.5; Feldmesse; Fürst Igor: Polovetzer Tänze",
    title: "Hrůša – Mahler/ Strauss/ Martinů (Matinee)",
    composers: "Strauss; Mahler; Martinu; Borodin",
    composerGivenNames: "Richard; Gustav; Bohuslav; Alexander",
    titles: "Hrůša – Mahler/ Strauss/ Martinů (Matinee)",
    duration: "01:39:00",
    soloistsLastNames: "Winters; Philharmonischer Chor München; Brückler",
    soloistsGivenNames: "Corinne; Jirí",
    instruments: "Solistin Stimmlage Sopran\" \"; Chor; Solist Stimmlage Bariton\" \"",
    conductorLastName: "Hrusa",
    conductorGivenNames: "Jakub",
    capacity: 1800,
    TExp: 3,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432276"
  },
  {
    date: "14.06.2026",
    start: "17:00:00",
    type: "Konzert",
    venue: "Halle E",
    city: "München",
    series: "",
    programm: "",
    title: "Symphonic Mob",
    composers: "",
    composerGivenNames: "",
    titles: "Symphonic Mob",
    duration: "00:00:00",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 0,
    TExp: 5,
    REnergy: 6,
    link: "https://www.mphil.de/konzerte-und-karten/kalender/konzerte/2026-06-14-4936"
  },
  {
    date: "18.06.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "B",
    programm: "Klarinettenkonzert A-Dur; Sinfonie Nr.9",
    title: "Mozart / Bruckner",
    composers: "Mozart; Bruckner",
    composerGivenNames: "Wolfgang Amadeus; Anton",
    titles: "Mozart / Bruckner",
    duration: "01:28:00",
    soloistsLastNames: "Gruber",
    soloistsGivenNames: "Alexandra Maria",
    instruments: "Klarinette",
    conductorLastName: "Mehta",
    conductorGivenNames: "Zubin",
    capacity: 1800,
    TExp: 1,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432200"
  },
  {
    date: "19.06.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "E4",
    programm: "Klarinettenkonzert A-Dur; Sinfonie Nr.9",
    title: "Mozart / Bruckner",
    composers: "Mozart; Bruckner",
    composerGivenNames: "Wolfgang Amadeus; Anton",
    titles: "Mozart / Bruckner",
    duration: "01:28:00",
    soloistsLastNames: "Gruber",
    soloistsGivenNames: "Alexandra Maria",
    instruments: "Klarinette",
    conductorLastName: "Mehta",
    conductorGivenNames: "Zubin",
    capacity: 1800,
    TExp: 1,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432325"
  },
  {
    date: "20.06.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "D",
    programm: "Klarinettenkonzert A-Dur; Sinfonie Nr.9",
    title: "Mozart / Bruckner",
    composers: "Mozart; Bruckner",
    composerGivenNames: "Wolfgang Amadeus; Anton",
    titles: "Mozart / Bruckner",
    duration: "01:28:00",
    soloistsLastNames: "Gruber",
    soloistsGivenNames: "Alexandra Maria",
    instruments: "Klarinette",
    conductorLastName: "Mehta",
    conductorGivenNames: "Zubin",
    capacity: 1800,
    TExp: 1,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432216"
  },
  {
    date: "21.06.2026",
    start: "11:00:00",
    type: "Kammerkonzert",
    venue: "Münchner Künstlerhaus",
    city: "München",
    series: "",
    programm: "Andante and Allegro; Divertimento für Oboenquintett C-Dur op. 9; Streichquartett Nr. 2; Oboenquartett F-Dur KV 370; Oboenquintett D-Dur op. 55 Nr. 3; Miniaturen",
    title: "Miniaturen - 8. Kammerkonzert",
    composers: "Elgar; Crusell; Schulhoff; Mozart; Boccherini; Cohen",
    composerGivenNames: "Edward; Bernhard Henrik; Erwin; Wolfgang Amadeus; Luigi; Ohad",
    titles: "Miniaturen - 8. Kammerkonzert",
    duration: "00:00:00",
    soloistsLastNames: "Funk-Hoever; Cohen; Schmitz; Rieke; Modersohn",
    soloistsGivenNames: "Elke; Ohad; Katharina; Jannis Michael; Marie-Luise",
    instruments: "Violoncello; 1. Violine; 2. Violine; Bratsche; Oboe",
    conductorLastName: "",
    conductorGivenNames: "",
    capacity: 400,
    TExp: 3,
    REnergy: 2,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432343"
  },
  {
    date: "24.06.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "A",
    programm: "Dance symphony; Sinfonie Nr.90; Gaîté parisienne; Songs",
    title: "Copland / Haydn / Offenbach / Weill",
    composers: "Copland; Haydn; Offenbach; Weill",
    composerGivenNames: "Aaron; Joseph; Jacques; Kurt",
    titles: "Copland / Haydn / Offenbach / Weill",
    duration: "01:21:00",
    soloistsLastNames: "Hannigan",
    soloistsGivenNames: "Barbara",
    instruments: "Solistin Stimmlage Sopran\" \"",
    conductorLastName: "Hannigan",
    conductorGivenNames: "Barbara",
    capacity: 1800,
    TExp: 5,
    REnergy: 6,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432185"
  },
  {
    date: "25.06.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "G4; F",
    programm: "Gaîté parisienne; Songs; Dance symphony; Sinfonie Nr.90",
    title: "Copland / Haydn / Offenbach / Weill",
    composers: "Offenbach; Weill; Copland; Haydn",
    composerGivenNames: "Jacques; Kurt; Aaron; Joseph",
    titles: "Copland / Haydn / Offenbach / Weill",
    duration: "02:42:00",
    soloistsLastNames: "Hannigan",
    soloistsGivenNames: "Barbara",
    instruments: "Solistin Stimmlage Sopran\" \"",
    conductorLastName: "Hannigan",
    conductorGivenNames: "Barbara",
    capacity: 1800,
    TExp: 5,
    REnergy: 6,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432264"
  },
  {
    date: "02.07.2026",
    start: "18:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "Jugendkonzert",
    programm: "Konzert für Violine und Orchester; Feuervogel-Suite (Fassung: 1919)",
    title: "4. Jugendkonzert",
    composers: "Dvorak; Strawinsky",
    composerGivenNames: "Antonin; Igor",
    titles: "4. Jugendkonzert",
    duration: "00:53:00",
    soloistsLastNames: "Faust",
    soloistsGivenNames: "Isabelle",
    instruments: "Solist /-in Violine\" \"",
    conductorLastName: "Popelka",
    conductorGivenNames: "Petr",
    capacity: 1800,
    TExp: 4,
    REnergy: 4,
    link: "https://www.mphil.de/konzerte-und-karten/kalender/konzerte/dvorak-henze-strawinsky-2026-07-02-4944"
  },
  {
    date: "03.07.2026",
    start: "19:30:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "C",
    programm: "Konzert für Violine und Orchester; Sebastian im Traum; Feuervogel-Suite (Fassung: 1919)",
    title: "Dvorak / Henze / Strawinsky",
    composers: "Dvorak; Henze; Strawinsky",
    composerGivenNames: "Antonin; Hans Werner; Igor",
    titles: "Dvorak / Henze / Strawinsky",
    duration: "01:08:00",
    soloistsLastNames: "Faust",
    soloistsGivenNames: "Isabelle",
    instruments: "Solist /-in Violine\" \"",
    conductorLastName: "Popelka",
    conductorGivenNames: "Petr",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432208"
  },
  {
    date: "04.07.2026",
    start: "19:00:00",
    type: "Konzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "K4",
    programm: "Konzert für Violine und Orchester; Sebastian im Traum; Feuervogel-Suite (Fassung: 1919)",
    title: "Dvorak / Henze / Strawinsky",
    composers: "Dvorak; Henze; Strawinsky",
    composerGivenNames: "Antonin; Hans Werner; Igor",
    titles: "Dvorak / Henze / Strawinsky",
    duration: "01:08:00",
    soloistsLastNames: "Faust",
    soloistsGivenNames: "Isabelle",
    instruments: "Solist /-in Violine\" \"",
    conductorLastName: "Popelka",
    conductorGivenNames: "Petr",
    capacity: 1800,
    TExp: 4,
    REnergy: 3,
    link: "https://tickets.muenchenticket.net/shop/142/link/event/432334"
  },
  {
    date: "08.07.2026",
    start: "10:00:00",
    type: "Kinderkonzert",
    venue: "Isarphilharmonie",
    city: "München",
    series: "",
    programm: "Ma mère l'Oye",
    title: "Ma Mère l’oie - Konzert für Vorschulgruppen und Grundschulklassen",
    composers: "Ravel",
    composerGivenNames: "Maurice",
    titles: "Ma Mère l’oie - Konzert für Vorschulgruppen und Grundschulklassen",
    duration: "00:29:00",
    soloistsLastNames: "",
    soloistsGivenNames: "",
    instruments: "",
    conductorLastName: "N.N.",
    conductorGivenNames: "",
    capacity: 1800,
    TExp: 3,
    REnergy: 5,
    link: "https://www.mphil.de/konzerte-und-karten/kalender/konzerte/ma-mere-loye"
  },
  {
    date: "12.07.2026",
    start: "20:00:00",
    type: "Konzert Open Air",
    venue: "Odeonsplatz, Feldherrnhalle",
    city: "München",
    series: "",
    programm: "Violinkonzert Nr. 1",
    title: "Klassik am Odeonsplatz",
    composers: "Bruch",
    composerGivenNames: "Max",
    titles: "Klassik am Odeonsplatz",
    duration: "00:25:00",
    soloistsLastNames: "Jansen",
    soloistsGivenNames: "Janine",
    instruments: "Solist /-in Violine\" \"",
    conductorLastName: "Shani",
    conductorGivenNames: "Lahav",
    capacity: 0,
    TExp: 3,
    REnergy: 2,
    link: "https://www.mphil.de/konzerte-und-karten/kalender/konzerte/2026-07-12-4948"
  }
];

export { concerts as CONCERTS };
